"""Dry-run argv tests for the VPS runsc/herdr launcher."""

from __future__ import annotations

import os
import re
import shlex
import subprocess
import tempfile
from pathlib import Path

import pytest

from creator_engine_validator import codex_launch_spec as launch_spec


REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "deploy" / "vps-runsc" / "run-vps-runsc.sh"
HOOK = REPO_ROOT / ".codex" / "hooks" / "ce-pretooluse-codex.py"
HOOK_COMMAND = (
    "PYTHONPATH=/workspace/creator-engine/validators "
    "python3 /workspace/creator-engine/.codex/hooks/ce-pretooluse-codex.py"
)


def expected_contained_codex_config() -> str:
    return (
        "# Generated by deploy/vps-runsc/run-vps-runsc.sh for contained VPS seats.\n"
        "# Nested Codex bubblewrap cannot run inside runsc/gVisor; gVisor is the sandbox.\n"
        'approval_policy = "never"\n'
        'sandbox_mode = "danger-full-access"\n'
        'model = "gpt-5.5"\n'
        'model_reasoning_effort = "high"\n'
        "allow_managed_hooks_only = true\n"
        "\n"
        "[tui]\n"
        'status_line = ["model-with-reasoning", "current-dir", "git-branch", "pull-request-number", "context-remaining", "context-used", "five-hour-limit", "weekly-limit"]\n'
        "status_line_use_colors = true\n"
        "\n"
        "[features]\n"
        "hooks = true\n"
        "\n"
        "[[hooks.PreToolUse]]\n"
        'matcher = "^(Bash|apply_patch|Edit|Write|MultiEdit|mcp__.*)$"\n'
        "\n"
        "[[hooks.PreToolUse.hooks]]\n"
        'type = "command"\n'
        f"command = '{HOOK_COMMAND}'\n"
        "timeout = 30\n"
        'statusMessage = "Checking CE Ring-1 policy"\n'
        "\n"
        '[projects."/workspace/creator-engine"]\n'
        'trust_level = "trusted"\n'
    )


def run_wrapper(*args: str, **env_overrides: str) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    with tempfile.TemporaryDirectory(prefix="creator-engine-vps-runsc-test-") as runtime_dir:
        env.update(
            {
                "CE_VPS_DRY_RUN": "1",
                "CE_VPS_REPO": "/repo/creator-engine",
                "CE_VPS_CODEX_HOME": "/home/seat/.codex",
                "CE_VPS_CODEX_BIN": "/opt/codex/bin/codex",
                "CE_VPS_CLAUDE_BIN": "/opt/claude/bin/claude",
                "CE_VPS_CONTAINER_USER": "seat",
                "CE_VPS_SEAT_LOG_DIR": f"{runtime_dir}/seat-logs",
                "CE_VPS_UID": "1234",
                "CE_VPS_GID": "5678",
                "CE_VPS_TTY_FLAGS": "-i",
                "XDG_RUNTIME_DIR": runtime_dir,
                "TERM": "xterm-256color",
                "CLAUDE_CODE_OAUTH_TOKEN": "synthetic-secret-token-value",
            }
        )
        env.update(env_overrides)
        return subprocess.run(
            ["bash", str(SCRIPT), "--dry-run", *args],
            cwd=REPO_ROOT,
            env=env,
            text=True,
            capture_output=True,
            check=False,
        )


def dry_run_argv(result: subprocess.CompletedProcess[str]) -> list[str]:
    assert result.returncode == 0, result.stderr
    return shlex.split(result.stdout)


def make_live_fake_docker(root: Path) -> Path:
    fake_bin = root / "bin"
    fake_bin.mkdir()
    docker = fake_bin / "docker"
    docker.write_text(
        "#!/bin/sh\n"
        "if [ \"$1\" = \"info\" ]; then\n"
        "  printf '{\"runsc-gvproxy-ptrace\":{}}\\n'\n"
        "  exit 0\n"
        "fi\n"
        "if [ \"$1\" = \"run\" ]; then\n"
        "  if [ -e \"${CE_TEST_HERDR_SESSION_FILE}\" ]; then\n"
        "    printf 'stale herdr session was still present before docker run\\n' >&2\n"
        "    exit 97\n"
        "  fi\n"
        "  printf 'fake-container-id\\n'\n"
        "  exit 0\n"
        "fi\n"
        "if [ \"$1\" = \"exec\" ]; then\n"
        "  case \" $* \" in\n"
        "    *' pane list'*) printf '{\"panes\":[{\"id\":\"w1:p1\"}]}\\n' ;;\n"
        "  esac\n"
        "  exit 0\n"
        "fi\n"
        "printf 'unexpected docker invocation: %s\\n' \"$*\" >&2\n"
        "exit 99\n",
        encoding="utf-8",
    )
    docker.chmod(0o755)
    return fake_bin


def run_live_wrapper_with_fake_docker(
    root: Path, *args: str, **env_overrides: str
) -> subprocess.CompletedProcess[str]:
    fake_bin = make_live_fake_docker(root)
    repo = root / "repo"
    codex_home = root / "codex-home"
    codex_bin = root / "codex"
    seat_logs = root / "seat-logs"
    repo.mkdir(exist_ok=True)
    codex_home.mkdir(exist_ok=True)
    codex_bin.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    codex_bin.chmod(0o755)

    env = os.environ.copy()
    env.update(
        {
            "CE_VPS_DRY_RUN": "0",
            "CE_VPS_REPO": str(repo),
            "CE_VPS_CODEX_HOME": str(codex_home),
            "CE_VPS_CODEX_BIN": str(codex_bin),
            "CE_VPS_CONTAINED_CODEX_CONFIG": str(root / "contained-codex.toml"),
            "CE_VPS_CONTAINER_USER": "seat",
            "CE_VPS_SEAT_LOG_DIR": str(seat_logs),
            "CE_VPS_UID": "1234",
            "CE_VPS_GID": "5678",
            "CE_VPS_TTY_FLAGS": "-i",
            "CE_TEST_HERDR_SESSION_FILE": str(
                seat_logs / "xdg" / "config" / "herdr" / "session.json"
            ),
            "PATH": f"{fake_bin}{os.pathsep}{env.get('PATH', '')}",
            "TERM": "xterm-256color",
        }
    )
    env.update(env_overrides)
    return subprocess.run(
        ["bash", str(SCRIPT), *args],
        cwd=REPO_ROOT,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )


def test_vps_launcher_shell_syntax_is_valid() -> None:
    result = subprocess.run(
        ["bash", "-n", str(SCRIPT)],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr


def test_codex_dry_run_uses_vps_containment_defaults() -> None:
    result = run_wrapper("exec", "summarize status")

    argv = dry_run_argv(result)

    assert argv[:2] == ["docker", "run"]
    assert "--runtime=runsc-gvproxy-ptrace" in argv
    assert "--network=host" in argv
    assert "--security-opt=no-new-privileges" in argv
    assert "--cap-drop=ALL" in argv
    assert "--user" in argv
    assert "1234:5678" in argv
    assert "creator-engine/codex-runsc:x86_64" in argv
    assert argv[-4:] == [
        "creator-engine/codex-runsc:x86_64",
        "exec",
        "--dangerously-bypass-hook-trust",
        "summarize status",
    ]
    assert "CE_DGX_HARNESS=codex" in argv
    assert "CE_DGX_HARNESS_MODE=exec" in argv
    assert "CE_SEAT_LOG_DIR=/var/log/ce-seat" in argv
    assert "CE_HERDR_SERVER_LOG=/var/log/ce-seat/herdr-server.log" in argv
    assert "CE_CODEX_STDERR_LOG=/var/log/ce-seat/codex-stderr.log" in argv
    assert "XDG_CONFIG_HOME=/var/log/ce-seat/xdg/config" in argv
    assert "XDG_STATE_HOME=/var/log/ce-seat/xdg/state" in argv
    assert "XDG_CACHE_HOME=/var/log/ce-seat/xdg/cache" in argv
    assert "CODEX_HOME=/home/seat/.codex" in argv
    assert "TERM=xterm-256color" in argv


def test_codex_dry_run_generates_contained_codex_config(tmp_path: Path) -> None:
    config_path = tmp_path / "contained-codex.toml"

    argv = dry_run_argv(
        run_wrapper("tui", CE_VPS_CONTAINED_CODEX_CONFIG=str(config_path))
    )

    assert any(
        arg
        == f"type=bind,source={config_path},target=/home/seat/.codex/config.toml,readonly"
        for arg in argv
    )
    text = config_path.read_text(encoding="utf-8")
    assert text == expected_contained_codex_config()
    assert "[[hooks.PreToolUse]]" in text
    assert HOOK_COMMAND in text
    assert HOOK.is_file()
    assert "--dangerously-bypass-hook-trust" in argv
    assert (
        argv[argv.index("creator-engine/codex-runsc:x86_64") + 1 :]
        == ["--dangerously-bypass-hook-trust"]
    )


def test_codex_tui_dry_run_ends_at_image_without_literal_tui_subcommand() -> None:
    argv = dry_run_argv(run_wrapper("tui"))

    assert argv[-2:] == [
        "creator-engine/codex-runsc:x86_64",
        "--dangerously-bypass-hook-trust",
    ]
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-codex"
    assert "CE_DGX_HARNESS=codex" in argv
    assert "CE_DGX_HARNESS_MODE=tui" in argv
    assert "tui" not in argv[argv.index("creator-engine/codex-runsc:x86_64") + 1 :]


def test_codex_dry_run_mounts_repo_codex_home_and_codex_binary() -> None:
    argv = dry_run_argv(run_wrapper("tui"))

    assert any(
        arg == "type=bind,source=/repo/creator-engine,target=/workspace/creator-engine"
        for arg in argv
    )
    assert any(
        arg == "type=bind,source=/home/seat/.codex,target=/home/seat/.codex"
        for arg in argv
    )
    assert any(
        arg.startswith("type=bind,source=") and arg.endswith(",target=/var/log/ce-seat")
        for arg in argv
    )
    assert any(
        arg.endswith(",target=/home/seat/.codex/config.toml,readonly") for arg in argv
    )
    assert any(
        arg == "type=bind,source=/opt/codex/bin/codex,target=/usr/local/bin/codex,readonly"
        for arg in argv
    )


def test_codex_npm_symlink_mounts_package_root_instead_of_broken_bin_symlink(
    tmp_path: Path,
) -> None:
    package_root = tmp_path / "npm-global" / "lib" / "node_modules" / "@openai" / "codex"
    package_bin = package_root / "bin" / "codex.js"
    package_bin.parent.mkdir(parents=True)
    package_bin.write_text("#!/usr/bin/env node\n", encoding="utf-8")
    package_bin.chmod(0o755)
    symlink_dir = tmp_path / "npm-global" / "bin"
    symlink_dir.mkdir(parents=True)
    codex_symlink = symlink_dir / "codex"
    codex_symlink.symlink_to("../lib/node_modules/@openai/codex/bin/codex.js")

    argv = dry_run_argv(run_wrapper("tui", CE_VPS_CODEX_BIN=str(codex_symlink)))

    assert any(
        arg
        == (
            f"type=bind,source={package_root},"
            "target=/usr/local/lib/node_modules/@openai/codex,readonly"
        )
        for arg in argv
    )
    assert not any(arg.endswith(",target=/usr/local/bin/codex,readonly") for arg in argv)


def test_controller_variant_uses_claude_harness_marker_without_credential_env() -> None:
    result = run_wrapper("--harness", "controller", "tui")

    argv = dry_run_argv(result)

    assert argv[-1] == "creator-engine/codex-runsc:x86_64"
    assert "CE_DGX_HARNESS=claude" in argv
    assert "CE_DGX_HARNESS_MODE=tui" in argv
    assert "--dangerously-bypass-hook-trust" not in argv
    assert "CLAUDE_CODE_OAUTH_TOKEN" not in argv
    assert "synthetic-secret-token-value" not in result.stdout
    assert "tui" not in argv[argv.index("creator-engine/codex-runsc:x86_64") + 1 :]
    assert any(
        arg == "type=bind,source=/opt/claude/bin/claude,target=/usr/local/bin/claude,readonly"
        for arg in argv
    )
    launch_spec.assert_no_container_credential_env(argv)


def test_vps_runsc_launch_guard_allows_clean_argv_with_host_credentials() -> None:
    result = run_wrapper(
        "exec",
        "summarize status",
        GH_TOKEN="ghs_vps_should_not_cross_container_boundary",
        GITHUB_TOKEN="github_pat_vps_should_not_cross_container_boundary",
        OPENAI_API_KEY="sk-vps-should-not-cross-container-boundary",
        BAO_TOKEN="hvs.vps_should_not_cross_container_boundary",
    )

    argv = dry_run_argv(result)
    rendered = "\n".join(argv)

    launch_spec.assert_no_container_credential_env(argv)
    for forbidden in (
        "GH_TOKEN",
        "GITHUB_TOKEN",
        "OPENAI_API_KEY",
        "BAO_TOKEN",
        "ghs_vps_should_not_cross_container_boundary",
        "github_pat_vps_should_not_cross_container_boundary",
        "sk-vps-should-not-cross-container-boundary",
        "hvs.vps_should_not_cross_container_boundary",
    ):
        assert forbidden not in rendered


def test_vps_runsc_launch_guard_denies_credential_env_carrier() -> None:
    clean_argv = dry_run_argv(run_wrapper("tui"))
    dirty_argv = clean_argv[:2] + ["--env", "CLAUDE_CODE_OAUTH_TOKEN"] + clean_argv[2:]

    findings = launch_spec.find_container_credential_env_carriers(dirty_argv)

    assert [finding.name for finding in findings] == ["CLAUDE_CODE_OAUTH_TOKEN"]
    with pytest.raises(launch_spec.GovernedCommandError):
        launch_spec.assert_no_container_credential_env(dirty_argv)


def test_detach_dry_run_uses_named_persistent_run_without_rm() -> None:
    argv = dry_run_argv(run_wrapper("--detach", "tui"))

    assert "-d" in argv
    assert "--name" in argv
    assert "ce-vps-codex" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-codex"
    assert "--rm" not in argv


def test_detach_relaunch_backs_up_stale_herdr_session_before_docker_run(
    tmp_path: Path,
) -> None:
    session_file = tmp_path / "seat-logs" / "xdg" / "config" / "herdr" / "session.json"
    session_file.parent.mkdir(parents=True)
    session_file.write_text('{"windows":[{"id":"w1","stale":true}]}\n', encoding="utf-8")

    result = run_live_wrapper_with_fake_docker(tmp_path, "--detach", "tui")

    assert result.returncode == 0, result.stderr
    assert not session_file.exists()
    backups = list(session_file.parent.glob("session.json.prelaunch-backup.*"))
    assert len(backups) == 1
    assert backups[0].read_text(encoding="utf-8") == '{"windows":[{"id":"w1","stale":true}]}\n'
    assert (tmp_path / "contained-codex.toml").read_text(
        encoding="utf-8"
    ) == expected_contained_codex_config()
    assert "backed up stale herdr session" in result.stderr
    assert "container ce-vps-codex is ready" in result.stdout


def test_detach_relaunch_dry_run_does_not_mutate_stale_herdr_session(
    tmp_path: Path,
) -> None:
    seat_logs = tmp_path / "seat-logs"
    session_file = seat_logs / "xdg" / "config" / "herdr" / "session.json"
    session_file.parent.mkdir(parents=True)
    stale_text = '{"windows":[{"id":"w1","stale":true}]}\n'
    session_file.write_text(stale_text, encoding="utf-8")

    result = run_wrapper(
        "--detach",
        "tui",
        CE_VPS_SEAT_LOG_DIR=str(seat_logs),
        CE_VPS_CONTAINED_CODEX_CONFIG=str(tmp_path / "contained-codex.toml"),
    )

    assert result.returncode == 0, result.stderr
    assert session_file.read_text(encoding="utf-8") == stale_text
    assert not list(session_file.parent.glob("session.json.prelaunch-backup.*"))


def test_relaunch_refuses_herdr_session_directory_symlink_escape(
    tmp_path: Path,
) -> None:
    seat_logs = tmp_path / "seat-logs"
    escaped = tmp_path / "escaped-herdr"
    (seat_logs / "xdg" / "config").mkdir(parents=True)
    escaped.mkdir()
    (seat_logs / "xdg" / "config" / "herdr").symlink_to(escaped)
    escaped_session = escaped / "session.json"
    escaped_session.write_text('{"windows":[{"id":"w1"}]}\n', encoding="utf-8")

    result = run_live_wrapper_with_fake_docker(tmp_path, "--detach", "tui")

    assert result.returncode == 66
    assert "outside seat log dir" in result.stderr
    assert escaped_session.exists()
    assert "stale herdr session was still present before docker run" not in result.stderr


def test_detach_after_harness_uses_harness_aware_container_name() -> None:
    argv = dry_run_argv(
        run_wrapper(
            "--harness",
            "controller",
            "--detach",
            "tui",
        )
    )

    assert "-d" in argv
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-controller"
    assert "--rm" not in argv


def test_detach_claude_harness_remains_tokenless() -> None:
    result = run_wrapper("--harness", "controller", "--detach", "tui")

    argv = dry_run_argv(result)
    assert "-d" in argv
    assert "CLAUDE_CODE_OAUTH_TOKEN" not in argv
    assert "synthetic-secret-token-value" not in result.stdout
    assert "synthetic-secret-token-value" not in result.stderr
    launch_spec.assert_no_container_credential_env(argv)


def test_detach_codex_harness_needs_no_optin_tokenless() -> None:
    # Codex detached carries no OAUTH token, so the guard does not apply.
    argv = dry_run_argv(run_wrapper("--detach", "tui"))
    assert "-d" in argv
    assert "CLAUDE_CODE_OAUTH_TOKEN" not in argv


def test_custom_container_name_propagates_to_name_flag() -> None:
    argv = dry_run_argv(
        run_wrapper("--detach", "tui", CE_VPS_CONTAINER_NAME="ce-vps-custom-seat")
    )

    assert argv[argv.index("--name") + 1] == "ce-vps-custom-seat"
    assert "--rm" not in argv


def test_detach_env_triggers_detached_argv() -> None:
    argv = dry_run_argv(run_wrapper("tui", CE_VPS_DETACH="1"))

    assert "-d" in argv
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-codex"
    assert "--rm" not in argv


def test_default_non_detached_exec_keeps_rm_without_detach_or_name_flags() -> None:
    argv = dry_run_argv(run_wrapper("exec", "hello"))

    assert "--rm" in argv
    assert "-d" not in argv
    assert "--name" not in argv


def test_default_tui_uses_canonical_container_name_without_detach() -> None:
    argv = dry_run_argv(run_wrapper("tui"))

    assert "--rm" in argv
    assert "-d" not in argv
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-codex"


def test_detach_dry_run_still_generates_pretrusting_contained_config(
    tmp_path: Path,
) -> None:
    config_path = tmp_path / "contained-codex.toml"

    argv = dry_run_argv(
        run_wrapper("--detach", "tui", CE_VPS_CONTAINED_CODEX_CONFIG=str(config_path))
    )

    assert any(
        arg
        == f"type=bind,source={config_path},target=/home/seat/.codex/config.toml,readonly"
        for arg in argv
    )
    assert config_path.read_text(encoding="utf-8") == expected_contained_codex_config()


def test_no_herdr_socket_path_carrier_or_host_socket_mount_reaches_docker_argv() -> None:
    result = run_wrapper(
        "tui",
        HERDR_SOCKET_PATH="/run/user/1000/herdr.sock",
        HERDR_SOCKET="/run/user/1000/legacy-herdr.sock",
        CE_DGX_HERDR_SOCKET_PATH="/run/user/1000/ce-dgx-herdr.sock",
        CE_DGX_SOCKET_PATH="/run/user/1000/ce-dgx-generic.sock",
    )

    argv = dry_run_argv(result)
    rendered = result.stdout

    assert "HERDR_SOCKET" not in rendered
    assert "CE_DGX_HERDR_SOCKET_PATH" not in rendered
    assert not re.search(r"CE_DGX_[A-Z0-9_]*SOCKET[A-Z0-9_]*=", rendered)
    assert "/run/user/1000/herdr.sock" not in rendered
    assert "/run/user/1000/legacy-herdr.sock" not in rendered
    assert "/run/user/1000/ce-dgx-herdr.sock" not in rendered
    assert "/run/user/1000/ce-dgx-generic.sock" not in rendered
    assert not any(
        arg.startswith("type=bind,") and (".sock" in arg or "socket" in arg.lower())
        for arg in argv
    )
