"""Static coherence guard for contained launcher-generated Codex configuration."""

from __future__ import annotations

import re
import tomllib
from pathlib import Path
from typing import Any

import pytest
import yaml


REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
MODEL_CANON_PATH = REPOSITORY_ROOT / "surfaces/model-canon.yaml"
LAUNCHERS = (
    (
        "ce-vps-codex",
        REPOSITORY_ROOT / "deploy/vps-runsc/run-vps-runsc.sh",
        "# Generated by deploy/vps-runsc/run-vps-runsc.sh for contained VPS seats.",
    ),
    (
        "ce-dgx-codex",
        REPOSITORY_ROOT / "deploy/dgx-runsc/run-codex-runsc.sh",
        "# Generated by deploy/dgx-runsc/run-codex-runsc.sh for contained DGX seats.",
    ),
)


def _config_heredoc(
    banner: str, opener: str = 'cat >"${CE_VPS_CONTAINED_CODEX_CONFIG}" <<CONFIG'
) -> str:
    return "\n".join(
        (
            opener,
            banner,
            'model = "gpt-5.6-terra"',
            'model_reasoning_effort = "high"',
            "CONFIG",
        )
    )


HEREDOC_OPENER = re.compile(
    r'^\s*cat\s+>\s*"\$\{CE_(?:VPS|DGX)_CONTAINED_CODEX_CONFIG\}"\s*'
    r"<<(?P<strip_tabs>-?)\s*(?P<delimiter>\S+)"
    r"\s*(?:#.*)?$"
)
ANY_HEREDOC_OPENER = re.compile(r"(?<!<)<<(?P<strip_tabs>-?)\s*(?P<delimiter>\S+)")


def _canon_pair(seat_id: str) -> tuple[str, str]:
    document = yaml.safe_load(MODEL_CANON_PATH.read_text(encoding="utf-8"))
    seats = document.get("seats") if isinstance(document, dict) else None
    if not isinstance(seats, list):
        raise AssertionError("model canon seats must be a list")

    matches = [seat for seat in seats if isinstance(seat, dict) and seat.get("id") == seat_id]
    if len(matches) != 1:
        raise AssertionError(f"expected exactly one model canon seat for {seat_id}")

    model = matches[0].get("model")
    effort = matches[0].get("model_reasoning_effort")
    if not isinstance(model, str) or not isinstance(effort, str):
        raise AssertionError(f"model canon seat {seat_id} must provide string model and effort")
    return model, effort


def _heredoc_delimiter(word: str) -> str | None:
    delimiter: list[str] = []
    index = 0

    while index < len(word):
        character = word[index]
        if character == "\\":
            index += 1
            if index == len(word) or not re.fullmatch(r"[A-Za-z0-9_]", word[index]):
                return None
            delimiter.append(word[index])
        elif character in "'\"":
            closing_index = word.find(character, index + 1)
            if closing_index == -1:
                return None
            quoted = word[index + 1 : closing_index]
            if not re.fullmatch(r"[A-Za-z0-9_]*", quoted):
                return None
            delimiter.append(quoted)
            index = closing_index
        elif re.fullmatch(r"[A-Za-z0-9_]", character):
            delimiter.append(character)
        else:
            return None
        index += 1

    result = "".join(delimiter)
    return result if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", result) else None


def _shell_code_line_indexes(lines: list[str]) -> set[int]:
    code_lines: set[int] = set()
    quote: str | None = None
    heredoc_closing: tuple[str, bool] | None = None

    for line_index, line in enumerate(lines):
        if heredoc_closing is not None:
            delimiter, strip_tabs = heredoc_closing
            candidate = line.rstrip("\r\n")
            if (candidate.lstrip("\t") if strip_tabs else candidate) == delimiter:
                heredoc_closing = None
            continue

        if quote is None:
            code_lines.add(line_index)

        index = 0
        while index < len(line):
            character = line[index]
            if quote == "'":
                if character == "'":
                    quote = None
            elif quote == '"':
                if character == "\\":
                    index += 1
                elif character == '"':
                    quote = None
            elif character == "#":
                break
            elif character in "'\"":
                quote = character
            elif character == "\\":
                index += 1
            index += 1

        if quote is None:
            opener = ANY_HEREDOC_OPENER.search(line)
            if opener is not None:
                delimiter = _heredoc_delimiter(opener.group("delimiter"))
                if delimiter is not None:
                    heredoc_closing = (delimiter, opener.group("strip_tabs") == "-")

    return code_lines


def _generated_toml_span(source: str, banner: str) -> tuple[int, int]:
    lines = source.splitlines(keepends=True)
    code_lines = _shell_code_line_indexes(lines)
    matching_spans: list[tuple[int, int]] = []
    offset = 0
    inactive_depth = 0

    for opener_index, opener_line in enumerate(lines):
        line_start = offset
        offset += len(opener_line)
        stripped = opener_line.strip()
        if opener_index in code_lines and re.fullmatch(r"if\s+false\s*;\s*then", stripped):
            inactive_depth += 1

        if opener_index not in code_lines or inactive_depth:
            if opener_index in code_lines and stripped == "fi" and inactive_depth:
                inactive_depth -= 1
            continue

        opener = HEREDOC_OPENER.search(opener_line)
        if opener is None:
            continue

        delimiter = _heredoc_delimiter(opener.group("delimiter"))
        if delimiter is None:
            continue
        strip_tabs = opener.group("strip_tabs") == "-"

        closing_index = next(
            (
                index
                for index in range(opener_index + 1, len(lines))
                if (
                    lines[index].rstrip("\r\n").lstrip("\t")
                    if strip_tabs
                    else lines[index].rstrip("\r\n")
                )
                == delimiter
            ),
            None,
        )
        if closing_index is None:
            if banner in "".join(lines[opener_index + 1 :]):
                raise AssertionError("generated configuration heredoc is unterminated")
            continue

        body_start = line_start + len(opener_line)
        body_end = body_start + sum(len(line) for line in lines[opener_index + 1 : closing_index])
        body = source[body_start:body_end].removesuffix("\n")
        if banner in body:
            matching_spans.append((body_start, body_end))

    if len(matching_spans) != 1:
        raise AssertionError("expected exactly one banner-containing generated configuration heredoc")
    return matching_spans[0]


def _generated_toml_body(source: str, banner: str) -> str:
    body_start, body_end = _generated_toml_span(source, banner)
    return source[body_start:body_end].removesuffix("\n")


def _replace_generated_toml_body(source: str, banner: str, replacement: str) -> str:
    body_start, body_end = _generated_toml_span(source, banner)
    return f"{source[:body_start]}{replacement}\n{source[body_end:]}"


def _launcher_pair(source: str, banner: str) -> tuple[str, str]:
    body = _generated_toml_body(source, banner)
    try:
        document: Any = tomllib.loads(body)
    except tomllib.TOMLDecodeError as error:
        raise AssertionError("generated configuration heredoc must be valid TOML") from error

    if not isinstance(document, dict):
        raise AssertionError("generated configuration TOML must be a table")
    model = document.get("model")
    effort = document.get("model_reasoning_effort")
    if not isinstance(model, str) or not isinstance(effort, str):
        raise AssertionError("generated configuration TOML must provide string model and effort")
    return model, effort


def _replace_toml_assignment(source: str, banner: str, key: str, replacement: str) -> str:
    body = _generated_toml_body(source, banner)
    changed_body, replacements = re.subn(
        rf"(?m)^{re.escape(key)} = \"[^\n]*\"$",
        replacement,
        body,
    )
    if replacements != 1:
        raise AssertionError(f"expected exactly one {key} assignment in generated TOML")
    return _replace_generated_toml_body(source, banner, changed_body)


def _assert_coherent(actual: tuple[str, str], expected: tuple[str, str]) -> None:
    assert actual == expected, "launcher-generated model and effort must match model canon"


@pytest.mark.parametrize(("seat_id", "launcher_path", "banner"), LAUNCHERS)
def test_generated_launcher_config_matches_model_canon(
    seat_id: str, launcher_path: Path, banner: str
) -> None:
    source = launcher_path.read_text(encoding="utf-8")
    _assert_coherent(_launcher_pair(source, banner), _canon_pair(seat_id))


@pytest.mark.parametrize(("seat_id", "launcher_path", "banner"), LAUNCHERS)
@pytest.mark.parametrize(
    ("key", "replacement"),
    (
        ("model", 'model = "different-model"'),
        ("model_reasoning_effort", 'model_reasoning_effort = "low"'),
    ),
)
def test_changed_generated_toml_assignment_fails_coherence(
    seat_id: str, launcher_path: Path, banner: str, key: str, replacement: str
) -> None:
    source = _replace_toml_assignment(
        launcher_path.read_text(encoding="utf-8"), banner, key, replacement
    )
    with pytest.raises(AssertionError, match="must match model canon"):
        _assert_coherent(_launcher_pair(source, banner), _canon_pair(seat_id))


@pytest.mark.parametrize(("seat_id", "launcher_path", "banner"), LAUNCHERS)
@pytest.mark.parametrize("key", ("model", "model_reasoning_effort"))
def test_missing_generated_toml_assignment_fails_closed(
    seat_id: str, launcher_path: Path, banner: str, key: str
) -> None:
    source = _replace_toml_assignment(
        launcher_path.read_text(encoding="utf-8"), banner, key, f"# missing {key}"
    )
    with pytest.raises(AssertionError, match="must provide string model and effort"):
        _launcher_pair(source, banner)


@pytest.mark.parametrize(("_seat_id", "launcher_path", "banner"), LAUNCHERS)
def test_duplicate_generated_toml_assignment_fails_closed(
    _seat_id: str, launcher_path: Path, banner: str
) -> None:
    source = launcher_path.read_text(encoding="utf-8")
    body = _generated_toml_body(source, banner)
    malformed_body = body.replace(
        'model = "gpt-5.6-terra"', 'model = "gpt-5.6-terra"\nmodel = "duplicate"', 1
    )
    malformed = _replace_generated_toml_body(source, banner, malformed_body)
    with pytest.raises(AssertionError, match="valid TOML"):
        _launcher_pair(malformed, banner)


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
def test_unterminated_generated_heredoc_fails_closed(
    _seat_id: str, _launcher_path: Path, banner: str
) -> None:
    source = (
        'cat >"${CE_VPS_CONTAINED_CODEX_CONFIG}" <<"CONFIG"\n'
        f'{banner}\nmodel = "gpt-5.6-terra"'
    )
    with pytest.raises(AssertionError, match="unterminated"):
        _launcher_pair(source, banner)


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
def test_duplicate_banner_containing_heredoc_fails_closed(
    _seat_id: str, _launcher_path: Path, banner: str
) -> None:
    toml = f'{banner}\nmodel = "gpt-5.6-terra"\nmodel_reasoning_effort = "high"'
    source = f"cat <<CONFIG\n{toml}\nCONFIG\ncat <<CONFIG\n{toml}\nCONFIG"
    with pytest.raises(AssertionError, match="exactly one"):
        _launcher_pair(source, banner)


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
@pytest.mark.parametrize(
    "opener",
    (
        'cat >"${CE_VPS_CONTAINED_CODEX_CONFIG}" <<\'CONFIG\'',
        'cat >"${CE_VPS_CONTAINED_CODEX_CONFIG}" <<"CONFIG"',
        'cat >"${CE_VPS_CONTAINED_CODEX_CONFIG}" <<\\CONFIG',
        'cat >"${CE_VPS_CONTAINED_CODEX_CONFIG}" <<C"ONFIG"',
    ),
)
def test_quoted_generated_heredoc_delimiters_are_accepted(
    _seat_id: str, _launcher_path: Path, banner: str, opener: str
) -> None:
    assert _launcher_pair(_config_heredoc(banner, opener), banner) == (
        "gpt-5.6-terra",
        "high",
    )


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
def test_tab_stripping_generated_heredoc_is_accepted(
    _seat_id: str, _launcher_path: Path, banner: str
) -> None:
    source = "\n".join(
        (
            'cat >"${CE_VPS_CONTAINED_CODEX_CONFIG}" <<-CONFIG',
            f"\t{banner}",
            '\tmodel = "gpt-5.6-terra"',
            '\tmodel_reasoning_effort = "high"',
            "\tCONFIG",
        )
    )
    assert _launcher_pair(source, banner) == ("gpt-5.6-terra", "high")


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
@pytest.mark.parametrize(
    "assignment",
    ("model = 1", "model_reasoning_effort = true"),
)
def test_non_string_generated_toml_assignments_fail_closed(
    _seat_id: str, _launcher_path: Path, banner: str, assignment: str
) -> None:
    key = assignment.partition(" =")[0]
    source = _config_heredoc(banner).replace(
        f'{key} = "gpt-5.6-terra"' if key == "model" else f'{key} = "high"', assignment
    )
    with pytest.raises(AssertionError, match="must provide string model and effort"):
        _launcher_pair(source, banner)


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
def test_malformed_generated_toml_fails_closed(
    _seat_id: str, _launcher_path: Path, banner: str
) -> None:
    source = _config_heredoc(banner).replace(
        'model = "gpt-5.6-terra"', "model = ["
    )
    with pytest.raises(AssertionError, match="valid TOML"):
        _launcher_pair(source, banner)


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
@pytest.mark.parametrize(
    "source",
    (
        "# cat >\"${CE_VPS_CONTAINED_CODEX_CONFIG}\" <<CONFIG\n"
        "{banner}\nmodel = \"gpt-5.6-terra\"\n"
        "model_reasoning_effort = \"high\"\nCONFIG",
        "example='cat >\"${CE_VPS_CONTAINED_CODEX_CONFIG}\" <<CONFIG\n"
        "{banner}\nmodel = \"gpt-5.6-terra\"\n"
        "model_reasoning_effort = \"high\"\nCONFIG'",
        "cat <<'EXAMPLE'\ncat >\"${CE_VPS_CONTAINED_CODEX_CONFIG}\" <<CONFIG\n"
        "{banner}\nmodel = \"gpt-5.6-terra\"\n"
        "model_reasoning_effort = \"high\"\nCONFIG\nEXAMPLE",
        "if false; then\ncat >\"${CE_VPS_CONTAINED_CODEX_CONFIG}\" <<CONFIG\n"
        "{banner}\nmodel = \"gpt-5.6-terra\"\n"
        "model_reasoning_effort = \"high\"\nCONFIG\nfi",
    ),
)
def test_heredoc_shaped_decoys_fail_closed(
    _seat_id: str, _launcher_path: Path, banner: str, source: str
) -> None:
    with pytest.raises(AssertionError, match="exactly one"):
        _launcher_pair(source.replace("{banner}", banner), banner)
