"""Dry-run argv and static entrypoint tests for the DGX Codex runsc wrapper."""

from __future__ import annotations

import os
import re
import shlex
import subprocess
import tempfile
from pathlib import Path

import pytest

from creator_engine_validator import codex_launch_spec as launch_spec


REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "deploy" / "dgx-runsc" / "run-codex-runsc.sh"
ENTRYPOINT = REPO_ROOT / "deploy" / "dgx-runsc" / "herdr-harness-entrypoint.sh"
DOCKERFILE = REPO_ROOT / "deploy" / "dgx-runsc" / "Dockerfile"
HOOK = REPO_ROOT / ".codex" / "hooks" / "ce-pretooluse-codex.py"
HOOK_COMMAND = (
    "CE_LEDGER_ROOT=/workspace/creator-engine/.ce/state/active-work-ledger "
    "PYTHONPATH=/workspace/creator-engine/validators "
    "python3 /workspace/creator-engine/.codex/hooks/ce-pretooluse-codex.py"
)


def expected_contained_codex_config() -> str:
    return (
        "# Generated by deploy/dgx-runsc/run-codex-runsc.sh for contained DGX seats.\n"
        "# Nested Codex bubblewrap cannot run inside runsc/gVisor; gVisor is the sandbox.\n"
        'approval_policy = "never"\n'
        'sandbox_mode = "danger-full-access"\n'
        'model = "gpt-5.6-terra"\n'
        'model_reasoning_effort = "high"\n'
        "allow_managed_hooks_only = true\n"
        "check_for_update_on_startup = false\n"
        "\n"
        "[tui]\n"
        'status_line = ["model-with-reasoning", "current-dir", "git-branch", "pull-request-number", "context-remaining", "context-used", "five-hour-limit", "weekly-limit"]\n'
        "status_line_use_colors = true\n"
        "\n"
        "[features]\n"
        "hooks = true\n"
        "\n"
        "[[hooks.PreToolUse]]\n"
        'matcher = "^(Bash|Read|apply_patch|Edit|Write|MultiEdit|mcp__.*)$"\n'
        "\n"
        "[[hooks.PreToolUse.hooks]]\n"
        'type = "command"\n'
        f"command = '{HOOK_COMMAND}'\n"
        "timeout = 30\n"
        'statusMessage = "Checking CE Ring-1 policy"\n'
        "\n"
        '[projects."/workspace/creator-engine"]\n'
        'trust_level = "trusted"\n'
    )


def run_wrapper(*args: str, **env_overrides: str | None) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.pop("CE_LEDGER_ROOT", None)
    env.pop("CE_REVIEWER_AUTHORITY_REF", None)
    with tempfile.TemporaryDirectory(prefix="creator-engine-dgx-runsc-test-") as runtime_dir:
        env.update(
            {
                "CE_DGX_DRY_RUN": "1",
                "CE_DGX_IMAGE": "creator-engine/codex-runsc:test",
                "CE_DGX_REPO": "/repo/creator-engine",
                "CE_DGX_CODEX_HOME": "/home/cedev4/.codex",
                "CE_DGX_SEAT_LOG_DIR": f"{runtime_dir}/seat-logs",
                "CE_DGX_UID": "1000",
                "CE_DGX_GID": "1000",
            }
        )
        for key, value in env_overrides.items():
            if value is None:
                env.pop(key, None)
            else:
                env[key] = value
        return subprocess.run(
            ["bash", str(SCRIPT), "--dry-run", *args],
            cwd=REPO_ROOT,
            env=env,
            text=True,
            capture_output=True,
            check=False,
        )


def run_wrapper_nondry_run_with_fake_docker(
    *args: str, **env_overrides: str | None
) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.pop("CE_LEDGER_ROOT", None)
    env.pop("CE_REVIEWER_AUTHORITY_REF", None)
    with tempfile.TemporaryDirectory(prefix="creator-engine-dgx-runsc-test-") as runtime_dir:
        root = Path(runtime_dir)
        fake_bin = root / "bin"
        repo = root / "repo"
        codex_home = root / "codex-home"
        fake_bin.mkdir()
        repo.mkdir()
        codex_home.mkdir()
        docker = fake_bin / "docker"
        docker.write_text(
            "#!/bin/sh\n"
            "if [ \"$1\" = \"info\" ]; then\n"
            "  printf '{\"runsc-gvproxy-ptrace\":{}}\\n'\n"
            "  exit 0\n"
            "fi\n"
            "printf 'unexpected docker invocation: %s\\n' \"$*\" >&2\n"
            "exit 99\n",
            encoding="utf-8",
        )
        docker.chmod(0o755)
        env.update(
            {
                "CE_DGX_DRY_RUN": "0",
                "CE_DGX_IMAGE": "creator-engine/codex-runsc:test",
                "CE_DGX_REPO": str(repo),
                "CE_DGX_CODEX_HOME": str(codex_home),
                "CE_DGX_CONTAINED_CODEX_CONFIG": str(root / "contained-codex.toml"),
                "CE_DGX_SEAT_LOG_DIR": str(root / "seat-logs"),
                "CE_DGX_UID": "1000",
                "CE_DGX_GID": "1000",
                "PATH": f"{fake_bin}{os.pathsep}{env.get('PATH', '')}",
            }
        )
        for key, value in env_overrides.items():
            if value is None:
                env.pop(key, None)
            else:
                env[key] = value
        return subprocess.run(
            ["bash", str(SCRIPT), *args],
            cwd=REPO_ROOT,
            env=env,
            text=True,
            capture_output=True,
            check=False,
        )


def make_live_fake_dgx_docker(root: Path) -> Path:
    fake_bin = root / "bin"
    fake_bin.mkdir()
    docker = fake_bin / "docker"
    docker.write_text(
        "#!/bin/sh\n"
        "if [ -n \"${CE_TEST_DOCKER_LOG:-}\" ]; then\n"
        "  printf '%s\\n' \"$*\" >> \"${CE_TEST_DOCKER_LOG}\"\n"
        "fi\n"
        "if [ \"$1\" = \"info\" ]; then\n"
        "  printf '{\"runsc-gvproxy-ptrace\":{}}\\n'\n"
        "  exit 0\n"
        "fi\n"
        "if [ \"$1\" = \"run\" ]; then\n"
        "  if [ -e \"${CE_TEST_HERDR_SESSION_FILE}\" ]; then\n"
        "    printf 'stale herdr session was still present before docker run\\n' >&2\n"
        "    exit 97\n"
        "  fi\n"
        "  printf 'fake-container-id\\n'\n"
        "  exit 0\n"
        "fi\n"
        "if [ \"$1\" = \"exec\" ]; then\n"
        "  case \" $* \" in\n"
        "    *' pane list'*)\n"
        "      if [ -n \"${CE_TEST_DOCKER_LOG:-}\" ]; then\n"
        "        printf '%s\\n' 'pane-list={\"panes\":[{\"id\":\"w1:p1\"}]}' >> \"${CE_TEST_DOCKER_LOG}\"\n"
        "      fi\n"
        "      printf '{\"panes\":[{\"id\":\"w1:p1\"}]}\\n'\n"
        "      ;;\n"
        "  esac\n"
        "  exit 0\n"
        "fi\n"
        "printf 'unexpected docker invocation: %s\\n' \"$*\" >&2\n"
        "exit 99\n",
        encoding="utf-8",
    )
    docker.chmod(0o755)
    return fake_bin


def run_live_dgx_wrapper_with_fake_docker(
    root: Path, *args: str, **env_overrides: str
) -> subprocess.CompletedProcess[str]:
    fake_bin = make_live_fake_dgx_docker(root)
    repo = root / "repo"
    codex_home = root / "codex-home"
    seat_logs = root / "seat-logs"
    repo.mkdir(exist_ok=True)
    codex_home.mkdir(exist_ok=True)

    env = os.environ.copy()
    env.pop("CE_LEDGER_ROOT", None)
    env.pop("CE_REVIEWER_AUTHORITY_REF", None)
    env.update(
        {
            "CE_DGX_DRY_RUN": "0",
            "CE_DGX_IMAGE": "creator-engine/codex-runsc:test",
            "CE_DGX_REPO": str(repo),
            "CE_DGX_CODEX_HOME": str(codex_home),
            "CE_DGX_CONTAINED_CODEX_CONFIG": str(root / "contained-codex.toml"),
            "CE_DGX_SEAT_LOG_DIR": str(seat_logs),
            "CE_DGX_UID": "1000",
            "CE_DGX_GID": "1000",
            "CE_DGX_DOCKER_NETWORK": "",
            "CE_DGX_NETWORK": "",
            "CE_TEST_HERDR_SESSION_FILE": str(
                seat_logs / "xdg" / "config" / "herdr" / "session.json"
            ),
            "CE_TEST_DOCKER_LOG": str(root / "docker-invocations.log"),
            "PATH": f"{fake_bin}{os.pathsep}{env.get('PATH', '')}",
            "TERM": "xterm-256color",
        }
    )
    env.update(env_overrides)
    return subprocess.run(
        ["bash", str(SCRIPT), *args],
        cwd=REPO_ROOT,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )


def dry_run_argv(result: subprocess.CompletedProcess[str]) -> list[str]:
    assert result.returncode == 0, result.stderr
    return shlex.split(result.stdout)


def test_codex_wrapper_shell_syntax_is_valid() -> None:
    for path in (SCRIPT, ENTRYPOINT):
        result = subprocess.run(
            ["bash", "-n", str(path)],
            cwd=REPO_ROOT,
            text=True,
            capture_output=True,
            check=False,
        )

        assert result.returncode == 0, result.stderr


def test_dgx_launcher_has_no_host_tmux_dependency() -> None:
    text = SCRIPT.read_text(encoding="utf-8")

    assert "command -v tmux" not in text
    assert "tmux " not in text


def test_codex_exec_dry_run_uses_runsc_image_entrypoint_and_harness_markers() -> None:
    result = run_wrapper("exec", "print working tree status")

    argv = dry_run_argv(result)

    assert argv[:2] == ["docker", "run"]
    assert "--runtime=runsc-gvproxy-ptrace" in argv
    assert "--security-opt=no-new-privileges" in argv
    assert "--cap-drop=ALL" in argv
    assert "--tmpfs" in argv
    assert "/run/creator-engine:uid=1000,gid=1000,mode=0700" in argv
    assert not any(arg.startswith("--network=") for arg in argv)
    assert "creator-engine/codex-runsc:test" in argv
    assert argv[-3:] == [
        "exec",
        "--dangerously-bypass-hook-trust",
        "print working tree status",
    ]
    assert "/usr/local/bin/codex" not in argv[argv.index("creator-engine/codex-runsc:test") + 1 :]
    assert "CE_DGX_HARNESS=codex" in argv
    assert "CE_DGX_HARNESS_BIN=/usr/local/bin/codex" in argv
    assert "CE_DGX_HERDR_SOCKET_PATH=/run/creator-engine/herdr/herdr.sock" in argv
    assert "CE_SEAT_LOG_DIR=/var/log/ce-seat" in argv
    assert "CE_HERDR_SERVER_LOG=/var/log/ce-seat/herdr-server.log" in argv
    assert "CE_CODEX_STDERR_LOG=/var/log/ce-seat/codex-stderr.log" in argv
    assert "XDG_CONFIG_HOME=/var/log/ce-seat/xdg/config" in argv
    assert "XDG_STATE_HOME=/var/log/ce-seat/xdg/state" in argv
    assert "XDG_CACHE_HOME=/var/log/ce-seat/xdg/cache" in argv
    assert "CE_DGX_TERMINAL_KIND=herdr" in argv
    assert "CE_TERMINAL_KIND=herdr" in argv
    assert not any(arg.startswith("HERDR_SOCKET_PATH=") for arg in argv)
    assert any(
        arg == "type=bind,source=/repo/creator-engine,target=/workspace/creator-engine"
        for arg in argv
    )
    assert any(
        arg == "type=bind,source=/home/cedev4/.codex,target=/home/cedev4/.codex"
        for arg in argv
    )
    assert any(
        arg.startswith("type=bind,source=") and arg.endswith(",target=/var/log/ce-seat")
        for arg in argv
    )
    assert any(
        arg.endswith(",target=/home/cedev4/.codex/config.toml,readonly") for arg in argv
    )
    assert not any(arg.endswith("target=/usr/local/bin/codex,readonly") for arg in argv)
    assert not any("/run/creator-engine/herdr" in arg and arg.startswith("type=bind,") for arg in argv)


def test_dgx_runsc_launch_guard_allows_clean_argv_with_host_credentials() -> None:
    result = run_wrapper(
        "exec",
        "print working tree status",
        GH_TOKEN="ghs_dgx_should_not_cross_container_boundary",
        GITHUB_TOKEN="github_pat_dgx_should_not_cross_container_boundary",
        OPENAI_API_KEY="sk-dgx-should-not-cross-container-boundary",
        CLAUDE_CODE_OAUTH_TOKEN="claude-dgx-should-not-cross-container-boundary",
        BAO_TOKEN="hvs.dgx_should_not_cross_container_boundary",
    )

    argv = dry_run_argv(result)
    rendered = "\n".join(argv)

    launch_spec.assert_no_container_credential_env(argv)
    for forbidden in (
        "GH_TOKEN",
        "GITHUB_TOKEN",
        "OPENAI_API_KEY",
        "CLAUDE_CODE_OAUTH_TOKEN",
        "BAO_TOKEN",
        "ghs_dgx_should_not_cross_container_boundary",
        "github_pat_dgx_should_not_cross_container_boundary",
        "sk-dgx-should-not-cross-container-boundary",
        "claude-dgx-should-not-cross-container-boundary",
        "hvs.dgx_should_not_cross_container_boundary",
    ):
        assert forbidden not in rendered


def test_dgx_runsc_launch_guard_denies_credential_env_carrier() -> None:
    clean_argv = dry_run_argv(run_wrapper("tui"))
    dirty_argv = clean_argv[:2] + ["--env", "GH_TOKEN"] + clean_argv[2:]

    findings = launch_spec.find_container_credential_env_carriers(dirty_argv)

    assert [finding.name for finding in findings] == ["GH_TOKEN"]
    with pytest.raises(launch_spec.GovernedCommandError):
        launch_spec.assert_no_container_credential_env(dirty_argv)


def test_codex_dry_run_generates_contained_codex_config(tmp_path: Path) -> None:
    config_path = tmp_path / "contained-codex.toml"

    argv = dry_run_argv(
        run_wrapper("tui", CE_DGX_CONTAINED_CODEX_CONFIG=str(config_path))
    )

    assert any(
        arg
        == (
            f"type=bind,source={config_path},"
            "target=/home/cedev4/.codex/config.toml,readonly"
        )
        for arg in argv
    )
    text = config_path.read_text(encoding="utf-8")
    assert text == expected_contained_codex_config()
    assert "[[hooks.PreToolUse]]" in text
    assert 'matcher = "^(Bash|Read|apply_patch|Edit|Write|MultiEdit|mcp__.*)$"' in text
    assert HOOK_COMMAND in text
    assert HOOK.is_file()
    assert "--dangerously-bypass-hook-trust" in argv
    assert (
        argv[argv.index("creator-engine/codex-runsc:test") + 1 :]
        == ["--dangerously-bypass-hook-trust"]
    )


def test_codex_config_embeds_container_visible_governance_refs(tmp_path: Path) -> None:
    config_path = tmp_path / "contained-codex.toml"
    host_ledger = "/repo/creator-engine/.ce/state/active-work-ledger"
    host_ref = "/repo/creator-engine/.ce/state/reviewer-authority.ce.yml"

    run_wrapper(
        "tui",
        CE_DGX_CONTAINED_CODEX_CONFIG=str(config_path),
        CE_LEDGER_ROOT=host_ledger,
        CE_REVIEWER_AUTHORITY_REF=host_ref,
    )

    text = config_path.read_text(encoding="utf-8")
    assert "allow_managed_hooks_only = true" in text
    assert (
        "CE_LEDGER_ROOT=/workspace/creator-engine/.ce/state/active-work-ledger "
        "CE_REVIEWER_AUTHORITY_REF=/workspace/creator-engine/.ce/state/reviewer-authority.ce.yml "
        "PYTHONPATH=/workspace/creator-engine/validators "
        "python3 /workspace/creator-engine/.codex/hooks/ce-pretooluse-codex.py"
    ) in text


def test_codex_tui_dry_run_lets_image_entrypoint_select_default_harness() -> None:
    result = run_wrapper("tui")

    argv = dry_run_argv(result)

    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-dgx-codex"
    assert argv[-2:] == [
        "creator-engine/codex-runsc:test",
        "--dangerously-bypass-hook-trust",
    ]


def test_codex_image_bakes_binary_without_host_binary_mount() -> None:
    argv = dry_run_argv(run_wrapper("tui"))

    assert not any(arg.endswith("target=/usr/local/bin/codex,readonly") for arg in argv)


def test_codex_detach_flag_dry_run_uses_detached_lifecycle_flags() -> None:
    result = run_wrapper("--detach", "exec", "hello")

    argv = dry_run_argv(result)

    assert argv[:2] == ["docker", "run"]
    assert "-d" in argv
    assert "--name" in argv
    assert "ce-dgx-codex" in argv
    assert argv[argv.index("--name") + 1] == "ce-dgx-codex"
    assert "--rm" not in argv
    # Posture invariants preserved in detached mode.
    assert "--runtime=runsc-gvproxy-ptrace" in argv
    assert "--security-opt=no-new-privileges" in argv
    assert "--cap-drop=ALL" in argv


def test_codex_default_dry_run_uses_detached_lifecycle_without_container_tty() -> None:
    result = run_wrapper("exec", "hello")

    argv = dry_run_argv(result)

    assert "-d" in argv
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-dgx-codex"
    assert "--rm" not in argv
    assert "-i" not in argv
    assert "-t" not in argv
    assert "-it" not in argv


def test_codex_detach_honors_explicit_tty_flags_for_operator_diagnostics() -> None:
    result = run_wrapper("--detach", "tui", CE_DGX_TTY_FLAGS="-t")

    argv = dry_run_argv(result)

    assert "-d" in argv
    assert "-t" in argv


def test_codex_detach_accepts_docker_restart_policy_for_supervision() -> None:
    result = run_wrapper("tui", CE_DGX_DOCKER_RESTART_POLICY="unless-stopped")

    argv = dry_run_argv(result)

    assert "--restart=unless-stopped" in argv
    assert "-d" in argv


def test_codex_detach_relaunch_backs_up_stale_herdr_session_before_docker_run(
    tmp_path: Path,
) -> None:
    session_file = tmp_path / "seat-logs" / "xdg" / "config" / "herdr" / "session.json"
    session_file.parent.mkdir(parents=True)
    session_file.write_text('{"windows":[{"id":"w1","stale":true}]}\n', encoding="utf-8")
    codex_session = tmp_path / "codex-home" / "sessions" / "session.json"
    codex_session.parent.mkdir(parents=True)
    codex_session_text = '{"codex":"preserve-session-history"}\n'
    codex_session.write_text(codex_session_text, encoding="utf-8")

    result = run_live_dgx_wrapper_with_fake_docker(tmp_path, "--detach", "tui")

    assert result.returncode == 0, result.stderr
    assert not session_file.exists()
    assert codex_session.read_text(encoding="utf-8") == codex_session_text
    backups = list(session_file.parent.glob("session.json.prelaunch-backup.*"))
    assert len(backups) == 1
    assert backups[0].read_text(encoding="utf-8") == '{"windows":[{"id":"w1","stale":true}]}\n'
    assert (tmp_path / "contained-codex.toml").read_text(
        encoding="utf-8"
    ) == expected_contained_codex_config()
    assert "backed up stale herdr session" in result.stderr
    assert "herdr is ready in detached container ce-dgx-codex" in result.stdout
    docker_log = (tmp_path / "docker-invocations.log").read_text(encoding="utf-8")
    assert "pane-list={\"panes\":[{\"id\":\"w1:p1\"}]}" in docker_log
    # The relaunch must not replay stale herdr windows (e.g. w2/w3 from a stale
    # session.json). Match the herdr window-id token form ("wN:" pane ref or
    # '"id":"wN"' json) rather than a bare "wN" substring: the captured docker
    # argv embeds the tmp_path, which under pytest-xdist contains worker ids like
    # ".../popen-gw3/..." that would spuriously match a bare "w3".
    for stale_window in ("w2", "w3"):
        assert f"{stale_window}:" not in docker_log
        assert f'"id":"{stale_window}"' not in docker_log


def test_codex_detach_relaunch_dry_run_does_not_mutate_stale_herdr_session(
    tmp_path: Path,
) -> None:
    seat_logs = tmp_path / "seat-logs"
    session_file = seat_logs / "xdg" / "config" / "herdr" / "session.json"
    session_file.parent.mkdir(parents=True)
    stale_text = '{"windows":[{"id":"w1","stale":true}]}\n'
    session_file.write_text(stale_text, encoding="utf-8")

    result = run_wrapper(
        "--detach",
        "tui",
        CE_DGX_SEAT_LOG_DIR=str(seat_logs),
        CE_DGX_CONTAINED_CODEX_CONFIG=str(tmp_path / "contained-codex.toml"),
    )

    assert result.returncode == 0, result.stderr
    assert session_file.read_text(encoding="utf-8") == stale_text
    assert not list(session_file.parent.glob("session.json.prelaunch-backup.*"))


def test_codex_detach_custom_container_name_propagates_to_name_flag() -> None:
    result = run_wrapper("--detach", "exec", "hello", CE_DGX_CONTAINER_NAME="my-seat")

    argv = dry_run_argv(result)

    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "my-seat"
    assert "ce-dgx-codex" not in argv
    assert "--rm" not in argv


def test_codex_foreground_dry_run_keeps_rm_and_no_detach_flags() -> None:
    result = run_wrapper("--foreground", "exec", "hello")

    argv = dry_run_argv(result)

    assert "--rm" in argv
    assert "-d" not in argv
    assert "--name" not in argv
    assert "-it" in argv


def test_codex_foreground_env_keeps_legacy_rm_path() -> None:
    result = run_wrapper("exec", "hello", CE_DGX_FOREGROUND="1")

    argv = dry_run_argv(result)

    assert "--rm" in argv
    assert "-d" not in argv


def test_codex_detach_env_without_flag_triggers_detached_argv() -> None:
    result = run_wrapper("exec", "hello", CE_DGX_DETACH="1")

    argv = dry_run_argv(result)

    assert "-d" in argv
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-dgx-codex"
    assert "--rm" not in argv


def test_entrypoint_fail_closed_and_uses_herdr_control_path_only_for_cli() -> None:
    text = ENTRYPOINT.read_text(encoding="utf-8")

    assert '[ -x "${HERDR_BIN}" ] || fail "herdr binary is not executable: ${HERDR_BIN}"' in text
    assert '[ -x "${HARNESS_BIN}" ] || fail "harness binary is not executable: ${HARNESS_BIN}"' in text
    assert 'DEFAULT_SOCKET="/run/creator-engine/herdr/herdr.sock"' in text
    assert 'install -d -m 0700 "${SOCKET_DIR}"' in text
    assert 'CE_SEAT_LOG_DIR="${CE_SEAT_LOG_DIR:-/var/log/ce-seat}"' in text
    assert 'CE_HERDR_SERVER_LOG="${CE_HERDR_SERVER_LOG:-${CE_SEAT_LOG_DIR}/herdr-server.log}"' in text
    assert 'CE_CODEX_STDERR_LOG="${CE_CODEX_STDERR_LOG:-${CE_SEAT_LOG_DIR}/codex-stderr.log}"' in text
    assert ': >>"${CE_HERDR_SERVER_LOG}"' in text
    assert ': >>"${CE_CODEX_STDERR_LOG}"' in text
    assert 'XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${CE_SEAT_LOG_DIR}/xdg/config}' in text
    assert 'HERDR_SOCKET_PATH="${CE_DGX_HERDR_SOCKET_PATH:-${DEFAULT_SOCKET}}" "${HERDR_BIN}" "$@"' in text
    assert 'HERDR_SOCKET_PATH="${SOCKET_PATH}" "${HERDR_BIN}" server >>"${CE_HERDR_SERVER_LOG}" 2>&1 &' in text
    assert 'herdr_cli workspace create --cwd "${WORKSPACE_CWD}" --label "${WORKSPACE_LABEL}"' in text
    assert "json_get_root_pane_id" in text
    assert '/bin/sh -c \'exec "$@" 2>>"${CE_CODEX_STDERR_LOG}"\'' in text
    assert 'herdr_cli pane run "${ROOT_PANE_ID}" "$(quote_cmd "${harness_cmd[@]}")"' in text
    assert "/usr/bin/env" in text
    assert "-i" in text
    assert "exec ${HARNESS_BIN}" not in text
    assert "raw harness" not in text.lower()


def test_entrypoint_starts_harness_with_clean_env_without_socket_carriers() -> None:
    text = ENTRYPOINT.read_text(encoding="utf-8")

    harness_block = text[text.index("harness_cmd=(") : text.index("harness_cmd+=(\"${HARNESS_BIN}\")")]

    assert "/usr/bin/env" in harness_block
    assert "-i" in harness_block
    assert "HERDR_SOCKET_PATH" not in harness_block
    assert "HERDR_SOCKET" not in harness_block
    assert not re.search(r"CE_DGX_[A-Z0-9_]*SOCKET[A-Z0-9_]*", harness_block)
    assert "CE_DGX_TERMINAL_KIND=herdr" in harness_block
    assert "CE_TERMINAL_KIND=herdr" in harness_block
    assert "CE_EGRESS_BROKER_SOCKET=${CE_EGRESS_BROKER_SOCKET}" in text
    assert "CE_SEAT_ID=${CE_SEAT_ID}" in text
    assert "CE_DGX_EGRESS_BROKER_SOCKET" not in harness_block


def test_dgx_socket_path_reaches_container_env_but_not_seat_env() -> None:
    socket_path = "/run/creator-engine/herdr/custom-herdr.sock"
    argv = dry_run_argv(run_wrapper("tui", CE_DGX_HERDR_SOCKET_PATH=socket_path))
    text = ENTRYPOINT.read_text(encoding="utf-8")
    harness_block = text[text.index("harness_cmd=(") : text.index("harness_cmd+=(\"${HARNESS_BIN}\")")]

    assert f"CE_DGX_HERDR_SOCKET_PATH={socket_path}" in argv
    assert "/usr/bin/env" in harness_block
    assert "-i" in harness_block
    assert "CE_DGX_HERDR_SOCKET_PATH" not in harness_block
    assert "HERDR_SOCKET_PATH" not in harness_block


def test_egress_broker_socket_mount_requires_explicit_seat_id() -> None:
    result = run_wrapper(
        "tui",
        CE_DGX_EGRESS_BROKER_SOCKET="/run/user/1000/creator-engine/egress-broker/dev-4.sock",
    )

    assert result.returncode == 2
    assert "CE_DGX_SEAT_ID must be set explicitly" in result.stderr


def test_egress_broker_socket_mount_rejects_non_broker_seat_id() -> None:
    result = run_wrapper(
        "tui",
        CE_DGX_SEAT_ID="ce-dgx-codex",
        CE_DGX_EGRESS_BROKER_SOCKET="/run/user/1000/creator-engine/egress-broker/dev-4.sock",
    )

    assert result.returncode == 2
    assert "CE_DGX_SEAT_ID must be a broker seat id like dev-4" in result.stderr


def test_egress_broker_socket_mount_rejects_empty_explicit_seat_id() -> None:
    result = run_wrapper(
        "tui",
        CE_DGX_SEAT_ID="",
        CE_DGX_EGRESS_BROKER_SOCKET="/run/user/1000/creator-engine/egress-broker/dev-4.sock",
    )

    assert result.returncode == 2
    assert "CE_DGX_SEAT_ID must be a broker seat id like dev-4" in result.stderr


def test_egress_broker_socket_mounts_only_socket_and_value_env() -> None:
    host_socket = "/run/user/1000/creator-engine/egress-broker/dev-4.sock"
    container_socket = "/run/ce-egress-broker.sock"
    argv = dry_run_argv(
        run_wrapper(
            "tui",
            CE_DGX_SEAT_ID="dev-4",
            CE_DGX_EGRESS_BROKER_SOCKET=host_socket,
            CE_DGX_CONTAINER_EGRESS_BROKER_SOCKET=container_socket,
            GITHUB_TOKEN="ghp_0123456789abcdef0123456789abcdef0123",
            GH_TOKEN="ghs_0123456789abcdef0123456789abcdef0123",
            OPENBAO_TOKEN="hvs.0123456789abcdef",
            CE_APP_KEY="-----BEGIN PRIVATE KEY-----",
            SSH_AUTH_SOCK="/tmp/ssh-agent.sock",
            DOCKER_HOST="unix:///var/run/docker.sock",
            CE_EGRESS_BROKER_CONFIG="/home/cedev4/.ce-egress/broker.json",
        )
    )

    assert f"CE_EGRESS_BROKER_SOCKET={container_socket}" in argv
    assert "CE_SEAT_ID=dev-4" in argv
    assert f"CE_DGX_EGRESS_BROKER_SOCKET={host_socket}" not in argv
    assert not any("CE_DGX_CONTAINER_EGRESS_BROKER_SOCKET=" in arg for arg in argv)
    assert any(
        arg == f"type=bind,source={host_socket},target={container_socket}"
        for arg in argv
    )
    rendered = "\n".join(argv)
    assert "ghp_0123456789abcdef0123456789abcdef0123" not in rendered
    assert "ghs_0123456789abcdef0123456789abcdef0123" not in rendered
    assert "hvs.0123456789abcdef" not in rendered
    assert "-----BEGIN PRIVATE KEY-----" not in rendered
    assert "/tmp/ssh-agent.sock" not in rendered
    assert "/var/run/docker.sock" not in rendered
    assert "/home/cedev4/.ce-egress/broker.json" not in rendered
    assert not any("GITHUB_TOKEN" in arg or "GH_TOKEN" in arg for arg in argv)
    assert not any(
        "OPENBAO" in arg
        or "APP_KEY" in arg
        or "SSH_AUTH_SOCK" in arg
        or "DOCKER_HOST" in arg
        or "CE_EGRESS_BROKER_CONFIG" in arg
        for arg in argv
    )


def test_egress_broker_socket_absent_fails_closed_before_docker_run_under_nondry_run() -> None:
    missing_socket = "/run/user/1000/creator-engine/egress-broker/missing.sock"
    result = run_wrapper_nondry_run_with_fake_docker(
        "tui",
        CE_DGX_SEAT_ID="dev-4",
        CE_DGX_EGRESS_BROKER_SOCKET=missing_socket,
    )

    assert result.returncode == 66
    assert f"egress broker socket not found: {missing_socket}" in result.stderr
    assert "unexpected docker invocation" not in result.stderr


def test_dockerfile_builds_herdr_from_source_and_uses_tini() -> None:
    text = DOCKERFILE.read_text(encoding="utf-8")

    assert "FROM ${RUST_SOURCE}:${RUST_VERSION}@sha256:${RUST_COMMIT_OR_DIGEST} AS herdr-builder" in text
    assert "FROM ${DEBIAN_SOURCE}:${DEBIAN_VERSION}@sha256:${DEBIAN_COMMIT_OR_DIGEST}" in text
    assert "ARG HERDR_SOURCE=UNSET" in text
    assert "ARG HERDR_COMMIT_OR_DIGEST=UNSET" in text
    assert "ARG ZIG_TOOLCHAIN_SOURCE=UNSET" in text
    assert "ARG ZIG_TOOLCHAIN_VERSION=UNSET" in text
    assert "cargo build --locked --release --bin herdr" in text
    assert "COPY --from=herdr-builder /build/herdr/target/release/herdr /usr/local/bin/herdr" in text
    assert "COPY herdr /usr/local/bin/herdr" not in text
    assert "bash" in text
    assert "procps" in text
    assert "python3" in text
    assert "tini" in text
    assert (
        'install -d -m 0700 -o "${CE_DGX_UID}" -g "${CE_DGX_GID}" /run/creator-engine/herdr'
        in text
    )
    assert "COPY deploy/dgx-runsc/herdr-harness-entrypoint.sh /usr/local/bin/ce-herdr-harness-entrypoint" in text
    assert "ARG CODEX_VERSION=0.144.1" in text
    assert "ARG CODEX_SHA256=9513fa3f5f4ad444ac1e40d972aef0e2664834ec54da987d54aba0dc2f13ea07" in text
    assert "sha256sum -c -" in text
    assert "codex-aarch64-unknown-linux-musl.tar.gz" in text
    assert "python3.14 -m venv /opt/ce-validator-venv" in text
    assert "COPY --from=validator-venv-builder /opt/ce-validator-venv /opt/ce-validator-venv" in text
    assert "/opt/ce-validator-venv/bin/ce --help" in text
    assert "check_for_update_on_startup = false" in text
    assert "test -x /usr/local/bin/herdr" in text
    assert (
        'ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/ce-herdr-harness-entrypoint"]'
        in text
    )


def test_dockerfile_disables_git_commit_signing_for_all_seat_users() -> None:
    text = DOCKERFILE.read_text(encoding="utf-8")

    assert "git config --system commit.gpgsign false" in text
    assert "git config --system --unset-all user.signingkey || true" in text
    assert "git config --system --unset-all gpg.format || true" in text


def test_dockerfile_venv_builder_installs_package_from_validators_subdir() -> None:
    text = DOCKERFILE.read_text(encoding="utf-8")

    assert (
        "/opt/ce-validator-venv/bin/pip install --no-index --no-build-isolation --no-deps validators/"
        in text
    )
