"""Static coherence guard for contained launcher-generated Codex configuration."""

from __future__ import annotations

import re
import tomllib
from pathlib import Path
from typing import Any

import pytest
import yaml


REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
MODEL_CANON_PATH = REPOSITORY_ROOT / "surfaces/model-canon.yaml"
LAUNCHERS = (
    (
        "ce-vps-codex",
        REPOSITORY_ROOT / "deploy/vps-runsc/run-vps-runsc.sh",
        "# Generated by deploy/vps-runsc/run-vps-runsc.sh for contained VPS seats.",
    ),
    (
        "ce-dgx-codex",
        REPOSITORY_ROOT / "deploy/dgx-runsc/run-codex-runsc.sh",
        "# Generated by deploy/dgx-runsc/run-codex-runsc.sh for contained DGX seats.",
    ),
)
HEREDOC_OPENER = re.compile(
    r"(?<!<)<<(?P<strip_tabs>-?)\s*"
    r"(?P<delimiter>'[^']+'|\"[^\"]+\"|[A-Za-z_][A-Za-z0-9_]*)"
    r"\s*(?:#.*)?$"
)


def _canon_pair(seat_id: str) -> tuple[str, str]:
    document = yaml.safe_load(MODEL_CANON_PATH.read_text(encoding="utf-8"))
    seats = document.get("seats") if isinstance(document, dict) else None
    if not isinstance(seats, list):
        raise AssertionError("model canon seats must be a list")

    matches = [seat for seat in seats if isinstance(seat, dict) and seat.get("id") == seat_id]
    if len(matches) != 1:
        raise AssertionError(f"expected exactly one model canon seat for {seat_id}")

    model = matches[0].get("model")
    effort = matches[0].get("model_reasoning_effort")
    if not isinstance(model, str) or not isinstance(effort, str):
        raise AssertionError(f"model canon seat {seat_id} must provide string model and effort")
    return model, effort


def _generated_toml_body(source: str, banner: str) -> str:
    lines = source.splitlines()
    matching_bodies: list[str] = []

    for opener_index, opener_line in enumerate(lines):
        opener = HEREDOC_OPENER.search(opener_line)
        if opener is None:
            continue

        delimiter = opener.group("delimiter")
        if delimiter[0] in "'\"":
            delimiter = delimiter[1:-1]
        strip_tabs = opener.group("strip_tabs") == "-"

        closing_index = next(
            (
                index
                for index in range(opener_index + 1, len(lines))
                if (lines[index].lstrip("\t") if strip_tabs else lines[index]) == delimiter
            ),
            None,
        )
        if closing_index is None:
            if banner in "\n".join(lines[opener_index + 1 :]):
                raise AssertionError("generated configuration heredoc is unterminated")
            continue

        body = "\n".join(lines[opener_index + 1 : closing_index])
        if banner in body:
            matching_bodies.append(body)

    if len(matching_bodies) != 1:
        raise AssertionError("expected exactly one banner-containing generated configuration heredoc")
    return matching_bodies[0]


def _launcher_pair(source: str, banner: str) -> tuple[str, str]:
    body = _generated_toml_body(source, banner)
    try:
        document: Any = tomllib.loads(body)
    except tomllib.TOMLDecodeError as error:
        raise AssertionError("generated configuration heredoc must be valid TOML") from error

    if not isinstance(document, dict):
        raise AssertionError("generated configuration TOML must be a table")
    model = document.get("model")
    effort = document.get("model_reasoning_effort")
    if not isinstance(model, str) or not isinstance(effort, str):
        raise AssertionError("generated configuration TOML must provide string model and effort")
    return model, effort


def _replace_toml_assignment(source: str, banner: str, key: str, replacement: str) -> str:
    body = _generated_toml_body(source, banner)
    changed_body, replacements = re.subn(
        rf"(?m)^{re.escape(key)} = \"[^\n]*\"$",
        replacement,
        body,
    )
    if replacements != 1:
        raise AssertionError(f"expected exactly one {key} assignment in generated TOML")
    return source.replace(body, changed_body, 1)


def _assert_coherent(actual: tuple[str, str], expected: tuple[str, str]) -> None:
    assert actual == expected, "launcher-generated model and effort must match model canon"


@pytest.mark.parametrize(("seat_id", "launcher_path", "banner"), LAUNCHERS)
def test_generated_launcher_config_matches_model_canon(
    seat_id: str, launcher_path: Path, banner: str
) -> None:
    source = launcher_path.read_text(encoding="utf-8")
    _assert_coherent(_launcher_pair(source, banner), _canon_pair(seat_id))


@pytest.mark.parametrize(("seat_id", "launcher_path", "banner"), LAUNCHERS)
@pytest.mark.parametrize(
    ("key", "replacement"),
    (
        ("model", 'model = "different-model"'),
        ("model_reasoning_effort", 'model_reasoning_effort = "low"'),
    ),
)
def test_changed_generated_toml_assignment_fails_coherence(
    seat_id: str, launcher_path: Path, banner: str, key: str, replacement: str
) -> None:
    source = _replace_toml_assignment(
        launcher_path.read_text(encoding="utf-8"), banner, key, replacement
    )
    with pytest.raises(AssertionError, match="must match model canon"):
        _assert_coherent(_launcher_pair(source, banner), _canon_pair(seat_id))


@pytest.mark.parametrize(("seat_id", "launcher_path", "banner"), LAUNCHERS)
@pytest.mark.parametrize("key", ("model", "model_reasoning_effort"))
def test_missing_generated_toml_assignment_fails_closed(
    seat_id: str, launcher_path: Path, banner: str, key: str
) -> None:
    source = _replace_toml_assignment(
        launcher_path.read_text(encoding="utf-8"), banner, key, f"# missing {key}"
    )
    with pytest.raises(AssertionError, match="must provide string model and effort"):
        _launcher_pair(source, banner)


@pytest.mark.parametrize(("_seat_id", "launcher_path", "banner"), LAUNCHERS)
def test_duplicate_generated_toml_assignment_fails_closed(
    _seat_id: str, launcher_path: Path, banner: str
) -> None:
    source = launcher_path.read_text(encoding="utf-8")
    body = _generated_toml_body(source, banner)
    malformed = source.replace(body, f'{body}\nmodel = "duplicate"', 1)
    with pytest.raises(AssertionError, match="valid TOML"):
        _launcher_pair(malformed, banner)


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
def test_unterminated_generated_heredoc_fails_closed(
    _seat_id: str, _launcher_path: Path, banner: str
) -> None:
    source = f'cat <<"CONFIG"\n{banner}\nmodel = "gpt-5.6-terra"'
    with pytest.raises(AssertionError, match="unterminated"):
        _launcher_pair(source, banner)


@pytest.mark.parametrize(("_seat_id", "_launcher_path", "banner"), LAUNCHERS)
def test_duplicate_banner_containing_heredoc_fails_closed(
    _seat_id: str, _launcher_path: Path, banner: str
) -> None:
    toml = f'{banner}\nmodel = "gpt-5.6-terra"\nmodel_reasoning_effort = "high"'
    source = f"cat <<CONFIG\n{toml}\nCONFIG\ncat <<CONFIG\n{toml}\nCONFIG"
    with pytest.raises(AssertionError, match="exactly one"):
        _launcher_pair(source, banner)
