"""Dry-run argv tests for the VPS runsc/herdr launcher."""

from __future__ import annotations

import os
import re
import shlex
import subprocess
import tempfile
from pathlib import Path

import pytest

from creator_engine_validator import codex_launch_spec as launch_spec


REPO_ROOT = Path(__file__).resolve().parents[3]
SCRIPT = REPO_ROOT / "deploy" / "vps-runsc" / "run-vps-runsc.sh"
HOOK = REPO_ROOT / ".codex" / "hooks" / "ce-pretooluse-codex.py"
HOOK_COMMAND = (
    "CE_LEDGER_ROOT=/workspace/creator-engine/.ce/state/active-work-ledger "
    "PYTHONPATH=/workspace/creator-engine/validators "
    "python3 /workspace/creator-engine/.codex/hooks/ce-pretooluse-codex.py"
)
RUNSC_IMAGE_RE = re.compile(
    r"^creator-engine/codex-runsc:x86_64(?:@sha256:[0-9a-fA-F]{64})?$"
)


def expected_contained_codex_config() -> str:
    return (
        "# Generated by deploy/vps-runsc/run-vps-runsc.sh for contained VPS seats.\n"
        "# Nested Codex bubblewrap cannot run inside runsc/gVisor; gVisor is the sandbox.\n"
        'approval_policy = "never"\n'
        'sandbox_mode = "danger-full-access"\n'
        'model = "gpt-5.6-terra"\n'
        'model_reasoning_effort = "high"\n'
        "allow_managed_hooks_only = true\n"
        "\n"
        "[tui]\n"
        'status_line = ["model-with-reasoning", "current-dir", "git-branch", "pull-request-number", "context-remaining", "context-used", "five-hour-limit", "weekly-limit"]\n'
        "status_line_use_colors = true\n"
        "\n"
        "[features]\n"
        "hooks = true\n"
        "\n"
        "[[hooks.PreToolUse]]\n"
        'matcher = "^(Bash|Read|apply_patch|Edit|Write|MultiEdit|mcp__.*)$"\n'
        "\n"
        "[[hooks.PreToolUse.hooks]]\n"
        'type = "command"\n'
        f"command = '{HOOK_COMMAND}'\n"
        "timeout = 30\n"
        'statusMessage = "Checking CE Ring-1 policy"\n'
        "\n"
        '[projects."/workspace/creator-engine"]\n'
        'trust_level = "trusted"\n'
    )


def run_wrapper(*args: str, **env_overrides: str | None) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.pop("CE_LEDGER_ROOT", None)
    env.pop("CE_REVIEWER_AUTHORITY_REF", None)
    with tempfile.TemporaryDirectory(prefix="creator-engine-vps-runsc-test-") as runtime_dir:
        env.update(
            {
                "CE_VPS_DRY_RUN": "1",
                "CE_VPS_REPO": "/repo/creator-engine",
                "CE_VPS_CODEX_HOME": "/home/seat/.codex",
                "CE_VPS_CODEX_BIN": "/opt/codex/bin/codex",
                "CE_VPS_CLAUDE_BIN": "/opt/claude/bin/claude",
                "CE_VPS_CONTAINER_USER": "seat",
                "CE_VPS_SEAT_LOG_DIR": f"{runtime_dir}/seat-logs",
                "CE_VPS_UID": "1234",
                "CE_VPS_GID": "5678",
                "XDG_RUNTIME_DIR": runtime_dir,
                "TERM": "xterm-256color",
                "CLAUDE_CODE_OAUTH_TOKEN": "synthetic-secret-token-value",
            }
        )
        for key, value in env_overrides.items():
            if value is None:
                env.pop(key, None)
            else:
                env[key] = value
        return subprocess.run(
            ["bash", str(SCRIPT), "--dry-run", *args],
            cwd=REPO_ROOT,
            env=env,
            text=True,
            capture_output=True,
            check=False,
        )


def dry_run_argv(result: subprocess.CompletedProcess[str]) -> list[str]:
    assert result.returncode == 0, result.stderr
    return shlex.split(result.stdout)


def runsc_image_index(argv: list[str]) -> int:
    matches = [index for index, arg in enumerate(argv) if RUNSC_IMAGE_RE.fullmatch(arg)]
    assert len(matches) == 1, argv
    return matches[0]


def make_live_fake_docker(root: Path) -> Path:
    fake_bin = root / "bin"
    fake_bin.mkdir()
    docker = fake_bin / "docker"
    docker.write_text(
        "#!/bin/sh\n"
        "if [ -n \"${CE_TEST_DOCKER_LOG:-}\" ]; then\n"
        "  printf '%s\\n' \"$*\" >> \"${CE_TEST_DOCKER_LOG}\"\n"
        "fi\n"
        "if [ \"$1\" = \"info\" ]; then\n"
        "  printf '{\"runsc-gvproxy-ptrace\":{}}\\n'\n"
        "  exit 0\n"
        "fi\n"
        "if [ \"$1\" = \"run\" ]; then\n"
        "  if [ -e \"${CE_TEST_HERDR_SESSION_FILE}\" ]; then\n"
        "    printf 'stale herdr session was still present before docker run\\n' >&2\n"
        "    exit 97\n"
        "  fi\n"
        "  printf 'fake-container-id\\n'\n"
        "  exit 0\n"
        "fi\n"
        "if [ \"$1\" = \"exec\" ]; then\n"
        "  case \" $* \" in\n"
        "    *' pane list'*)\n"
        "      if [ -n \"${CE_TEST_DOCKER_LOG:-}\" ]; then\n"
        "        printf '%s\\n' 'pane-list={\"panes\":[{\"id\":\"w1:p1\"}]}' >> \"${CE_TEST_DOCKER_LOG}\"\n"
        "      fi\n"
        "      printf '{\"panes\":[{\"id\":\"w1:p1\"}]}\\n'\n"
        "      ;;\n"
        "  esac\n"
        "  exit 0\n"
        "fi\n"
        "printf 'unexpected docker invocation: %s\\n' \"$*\" >&2\n"
        "exit 99\n",
        encoding="utf-8",
    )
    docker.chmod(0o755)
    return fake_bin


def run_live_wrapper_with_fake_docker(
    root: Path, *args: str, **env_overrides: str
) -> subprocess.CompletedProcess[str]:
    fake_bin = make_live_fake_docker(root)
    repo = root / "repo"
    codex_home = root / "codex-home"
    codex_bin = root / "codex"
    seat_logs = root / "seat-logs"
    repo.mkdir(exist_ok=True)
    codex_home.mkdir(exist_ok=True)
    codex_bin.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    codex_bin.chmod(0o755)

    env = os.environ.copy()
    env.pop("CE_LEDGER_ROOT", None)
    env.pop("CE_REVIEWER_AUTHORITY_REF", None)
    env.update(
        {
            "CE_VPS_DRY_RUN": "0",
            "CE_VPS_REPO": str(repo),
            "CE_VPS_CODEX_HOME": str(codex_home),
            "CE_VPS_CODEX_BIN": str(codex_bin),
            "CE_VPS_CONTAINED_CODEX_CONFIG": str(root / "contained-codex.toml"),
            "CE_VPS_CONTAINER_USER": "seat",
            "CE_VPS_SEAT_LOG_DIR": str(seat_logs),
            "CE_VPS_UID": "1234",
            "CE_VPS_GID": "5678",
            "CE_TEST_HERDR_SESSION_FILE": str(
                seat_logs / "xdg" / "config" / "herdr" / "session.json"
            ),
            "CE_TEST_DOCKER_LOG": str(root / "docker-invocations.log"),
            "PATH": f"{fake_bin}{os.pathsep}{env.get('PATH', '')}",
            "TERM": "xterm-256color",
        }
    )
    env.update(env_overrides)
    return subprocess.run(
        ["bash", str(SCRIPT), *args],
        cwd=REPO_ROOT,
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )


def test_vps_launcher_shell_syntax_is_valid() -> None:
    result = subprocess.run(
        ["bash", "-n", str(SCRIPT)],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr


def test_vps_launcher_has_no_host_tmux_dependency() -> None:
    text = SCRIPT.read_text(encoding="utf-8")

    assert "command -v tmux" not in text
    assert "tmux " not in text


def test_codex_dry_run_uses_vps_containment_defaults() -> None:
    result = run_wrapper("exec", "summarize status")

    argv = dry_run_argv(result)

    assert argv[:2] == ["docker", "run"]
    assert "--runtime=runsc-gvproxy-ptrace" in argv
    assert "--network=host" in argv
    assert "--security-opt=no-new-privileges" in argv
    assert "--cap-drop=ALL" in argv
    assert "--user" in argv
    assert "1234:5678" in argv
    image_index = runsc_image_index(argv)
    assert image_index == len(argv) - 4
    assert argv[image_index + 1 :] == [
        "exec",
        "--dangerously-bypass-hook-trust",
        "summarize status",
    ]
    assert "CE_DGX_HARNESS=codex" in argv
    assert "CE_DGX_HARNESS_MODE=exec" in argv
    assert "CE_SEAT_LOG_DIR=/var/log/ce-seat" in argv
    assert "CE_HERDR_SERVER_LOG=/var/log/ce-seat/herdr-server.log" in argv
    assert "CE_CODEX_STDERR_LOG=/var/log/ce-seat/codex-stderr.log" in argv
    assert "XDG_CONFIG_HOME=/var/log/ce-seat/xdg/config" in argv
    assert "XDG_STATE_HOME=/var/log/ce-seat/xdg/state" in argv
    assert "XDG_CACHE_HOME=/var/log/ce-seat/xdg/cache" in argv
    assert "CODEX_HOME=/home/seat/.codex" in argv
    assert "TERM=xterm-256color" in argv


def test_codex_dry_run_generates_contained_codex_config(tmp_path: Path) -> None:
    config_path = tmp_path / "contained-codex.toml"

    argv = dry_run_argv(
        run_wrapper("tui", CE_VPS_CONTAINED_CODEX_CONFIG=str(config_path))
    )

    assert any(
        arg
        == f"type=bind,source={config_path},target=/home/seat/.codex/config.toml,readonly"
        for arg in argv
    )
    text = config_path.read_text(encoding="utf-8")
    assert text == expected_contained_codex_config()
    assert "[[hooks.PreToolUse]]" in text
    assert 'matcher = "^(Bash|Read|apply_patch|Edit|Write|MultiEdit|mcp__.*)$"' in text
    assert HOOK_COMMAND in text
    assert HOOK.is_file()
    assert "--dangerously-bypass-hook-trust" in argv
    image_index = runsc_image_index(argv)
    assert argv[image_index + 1 :] == ["--dangerously-bypass-hook-trust"]


def test_codex_config_embeds_container_visible_governance_refs(tmp_path: Path) -> None:
    config_path = tmp_path / "contained-codex.toml"
    host_ledger = "/repo/creator-engine/.ce/state/active-work-ledger"
    host_ref = "/repo/creator-engine/.ce/state/reviewer-authority.ce.yml"

    run_wrapper(
        "tui",
        CE_VPS_CONTAINED_CODEX_CONFIG=str(config_path),
        CE_LEDGER_ROOT=host_ledger,
        CE_REVIEWER_AUTHORITY_REF=host_ref,
    )

    text = config_path.read_text(encoding="utf-8")
    assert "allow_managed_hooks_only = true" in text
    assert (
        "CE_LEDGER_ROOT=/workspace/creator-engine/.ce/state/active-work-ledger "
        "CE_REVIEWER_AUTHORITY_REF=/workspace/creator-engine/.ce/state/reviewer-authority.ce.yml "
        "PYTHONPATH=/workspace/creator-engine/validators "
        "python3 /workspace/creator-engine/.codex/hooks/ce-pretooluse-codex.py"
    ) in text


def test_codex_tui_dry_run_ends_at_image_without_literal_tui_subcommand() -> None:
    argv = dry_run_argv(run_wrapper("tui"))

    image_index = runsc_image_index(argv)
    assert image_index == len(argv) - 2
    assert argv[image_index + 1] == "--dangerously-bypass-hook-trust"
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-codex"
    assert "CE_DGX_HARNESS=codex" in argv
    assert "CE_DGX_HARNESS_MODE=tui" in argv
    assert "tui" not in argv[image_index + 1 :]


def test_codex_dry_run_mounts_repo_codex_home_and_codex_binary() -> None:
    argv = dry_run_argv(run_wrapper("tui"))

    assert any(
        arg == "type=bind,source=/repo/creator-engine,target=/workspace/creator-engine"
        for arg in argv
    )
    assert any(
        arg == "type=bind,source=/home/seat/.codex,target=/home/seat/.codex"
        for arg in argv
    )
    assert any(
        arg.startswith("type=bind,source=") and arg.endswith(",target=/var/log/ce-seat")
        for arg in argv
    )
    assert any(
        arg.endswith(",target=/home/seat/.codex/config.toml,readonly") for arg in argv
    )
    assert any(
        arg == "type=bind,source=/opt/codex/bin/codex,target=/usr/local/bin/codex,readonly"
        for arg in argv
    )


def test_codex_npm_symlink_mounts_package_root_instead_of_broken_bin_symlink(
    tmp_path: Path,
) -> None:
    package_root = tmp_path / "npm-global" / "lib" / "node_modules" / "@openai" / "codex"
    package_bin = package_root / "bin" / "codex.js"
    package_bin.parent.mkdir(parents=True)
    package_bin.write_text("#!/usr/bin/env node\n", encoding="utf-8")
    package_bin.chmod(0o755)
    symlink_dir = tmp_path / "npm-global" / "bin"
    symlink_dir.mkdir(parents=True)
    codex_symlink = symlink_dir / "codex"
    codex_symlink.symlink_to("../lib/node_modules/@openai/codex/bin/codex.js")

    argv = dry_run_argv(run_wrapper("tui", CE_VPS_CODEX_BIN=str(codex_symlink)))

    assert any(
        arg
        == (
            f"type=bind,source={package_root},"
            "target=/usr/local/lib/node_modules/@openai/codex,readonly"
        )
        for arg in argv
    )
    assert not any(arg.endswith(",target=/usr/local/bin/codex,readonly") for arg in argv)


def test_controller_variant_uses_claude_harness_marker_without_credential_env() -> None:
    result = run_wrapper("--harness", "controller", "tui")

    argv = dry_run_argv(result)

    image_index = runsc_image_index(argv)
    assert image_index == len(argv) - 1
    assert "CE_DGX_HARNESS=claude" in argv
    assert "CE_DGX_HARNESS_MODE=tui" in argv
    assert "--dangerously-bypass-hook-trust" not in argv
    assert "CLAUDE_CODE_OAUTH_TOKEN" not in argv
    assert "synthetic-secret-token-value" not in result.stdout
    assert "tui" not in argv[image_index + 1 :]
    assert any(
        arg == "type=bind,source=/opt/claude/bin/claude,target=/usr/local/bin/claude,readonly"
        for arg in argv
    )
    launch_spec.assert_no_container_credential_env(argv)


def test_vps_runsc_launch_guard_allows_clean_argv_with_host_credentials() -> None:
    result = run_wrapper(
        "exec",
        "summarize status",
        GH_TOKEN="ghs_vps_should_not_cross_container_boundary",
        GITHUB_TOKEN="github_pat_vps_should_not_cross_container_boundary",
        OPENAI_API_KEY="sk-vps-should-not-cross-container-boundary",
        BAO_TOKEN="hvs.vps_should_not_cross_container_boundary",
    )

    argv = dry_run_argv(result)
    rendered = "\n".join(argv)

    launch_spec.assert_no_container_credential_env(argv)
    for forbidden in (
        "GH_TOKEN",
        "GITHUB_TOKEN",
        "OPENAI_API_KEY",
        "BAO_TOKEN",
        "ghs_vps_should_not_cross_container_boundary",
        "github_pat_vps_should_not_cross_container_boundary",
        "sk-vps-should-not-cross-container-boundary",
        "hvs.vps_should_not_cross_container_boundary",
    ):
        assert forbidden not in rendered


def test_vps_runsc_launch_guard_denies_credential_env_carrier() -> None:
    clean_argv = dry_run_argv(run_wrapper("tui"))
    dirty_argv = clean_argv[:2] + ["--env", "CLAUDE_CODE_OAUTH_TOKEN"] + clean_argv[2:]

    findings = launch_spec.find_container_credential_env_carriers(dirty_argv)

    assert [finding.name for finding in findings] == ["CLAUDE_CODE_OAUTH_TOKEN"]
    with pytest.raises(launch_spec.GovernedCommandError):
        launch_spec.assert_no_container_credential_env(dirty_argv)


def test_default_dry_run_uses_detached_named_persistent_run_without_rm() -> None:
    argv = dry_run_argv(run_wrapper("tui"))

    assert "-d" in argv
    assert "--name" in argv
    assert "ce-vps-codex" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-codex"
    assert "--rm" not in argv
    assert "-i" not in argv
    assert "-t" not in argv
    assert "-it" not in argv
    assert argv[runsc_image_index(argv)] == "creator-engine/codex-runsc:x86_64"


def test_vps_image_override_is_preserved_without_a_stale_default_digest() -> None:
    argv = dry_run_argv(run_wrapper("tui", CE_VPS_IMAGE="registry.example/approved:custom"))
    assert "registry.example/approved:custom" in argv
    assert "@sha256:" not in SCRIPT.read_text(encoding="utf-8")


def test_detach_dry_run_honors_explicit_tty_flags_for_operator_diagnostics() -> None:
    argv = dry_run_argv(run_wrapper("--detach", "tui", CE_VPS_TTY_FLAGS="-t"))

    assert "-d" in argv
    assert "-t" in argv


def test_detach_dry_run_accepts_docker_restart_policy_for_supervision() -> None:
    argv = dry_run_argv(
        run_wrapper("tui", CE_VPS_DOCKER_RESTART_POLICY="unless-stopped")
    )

    assert "--restart=unless-stopped" in argv
    assert "-d" in argv


def test_detach_relaunch_backs_up_stale_herdr_session_before_docker_run(
    tmp_path: Path,
) -> None:
    session_file = tmp_path / "seat-logs" / "xdg" / "config" / "herdr" / "session.json"
    session_file.parent.mkdir(parents=True)
    session_file.write_text('{"windows":[{"id":"w1","stale":true}]}\n', encoding="utf-8")
    codex_session = tmp_path / "codex-home" / "sessions" / "session.json"
    codex_session.parent.mkdir(parents=True)
    codex_session_text = '{"codex":"preserve-session-history"}\n'
    codex_session.write_text(codex_session_text, encoding="utf-8")

    result = run_live_wrapper_with_fake_docker(tmp_path, "--detach", "tui")

    assert result.returncode == 0, result.stderr
    assert not session_file.exists()
    assert codex_session.read_text(encoding="utf-8") == codex_session_text
    backups = list(session_file.parent.glob("session.json.prelaunch-backup.*"))
    assert len(backups) == 1
    assert backups[0].read_text(encoding="utf-8") == '{"windows":[{"id":"w1","stale":true}]}\n'
    assert (tmp_path / "contained-codex.toml").read_text(
        encoding="utf-8"
    ) == expected_contained_codex_config()
    assert "backed up stale herdr session" in result.stderr
    assert "container ce-vps-codex is ready" in result.stdout
    docker_log = (tmp_path / "docker-invocations.log").read_text(encoding="utf-8")
    commands = docker_log.splitlines()
    assert any(command == "rm -f ce-vps-codex" for command in commands)
    assert any(command.startswith("run -d --name ce-vps-codex ") for command in commands)
    assert any(command.startswith("exec ce-vps-codex test -S ") for command in commands)
    assert any(command.startswith("exec --env HERDR_SOCKET_PATH=") and " ce-vps-codex herdr pane list" in command for command in commands)
    assert "ancestor=" not in docker_log
    assert "pane-list={\"panes\":[{\"id\":\"w1:p1\"}]}" in docker_log
    # The relaunch must not replay stale herdr windows (e.g. w2/w3 from a stale
    # session.json). Match the herdr window-id token form ("wN:" pane ref or
    # '"id":"wN"' json) rather than a bare "wN" substring: the captured docker
    # argv embeds the tmp_path, which under pytest-xdist contains worker ids like
    # ".../popen-gw3/..." that would spuriously match a bare "w3".
    for stale_window in ("w2", "w3"):
        assert f"{stale_window}:" not in docker_log
        assert f'"id":"{stale_window}"' not in docker_log


def test_detach_relaunch_dry_run_does_not_mutate_stale_herdr_session(
    tmp_path: Path,
) -> None:
    seat_logs = tmp_path / "seat-logs"
    session_file = seat_logs / "xdg" / "config" / "herdr" / "session.json"
    session_file.parent.mkdir(parents=True)
    stale_text = '{"windows":[{"id":"w1","stale":true}]}\n'
    session_file.write_text(stale_text, encoding="utf-8")

    result = run_wrapper(
        "--detach",
        "tui",
        CE_VPS_SEAT_LOG_DIR=str(seat_logs),
        CE_VPS_CONTAINED_CODEX_CONFIG=str(tmp_path / "contained-codex.toml"),
    )

    assert result.returncode == 0, result.stderr
    assert session_file.read_text(encoding="utf-8") == stale_text
    assert not list(session_file.parent.glob("session.json.prelaunch-backup.*"))


def test_relaunch_refuses_herdr_session_directory_symlink_escape(
    tmp_path: Path,
) -> None:
    seat_logs = tmp_path / "seat-logs"
    escaped = tmp_path / "escaped-herdr"
    (seat_logs / "xdg" / "config").mkdir(parents=True)
    escaped.mkdir()
    (seat_logs / "xdg" / "config" / "herdr").symlink_to(escaped)
    escaped_session = escaped / "session.json"
    escaped_session.write_text('{"windows":[{"id":"w1"}]}\n', encoding="utf-8")

    result = run_live_wrapper_with_fake_docker(tmp_path, "--detach", "tui")

    assert result.returncode == 66
    assert "outside seat log dir" in result.stderr
    assert escaped_session.exists()
    assert "stale herdr session was still present before docker run" not in result.stderr


def test_detach_after_harness_uses_harness_aware_container_name() -> None:
    argv = dry_run_argv(
        run_wrapper(
            "--harness",
            "controller",
            "--detach",
            "tui",
        )
    )

    assert "-d" in argv
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-controller"
    assert "--rm" not in argv


def test_detach_claude_harness_remains_tokenless() -> None:
    result = run_wrapper("--harness", "controller", "--detach", "tui")

    argv = dry_run_argv(result)
    assert "-d" in argv
    assert "CLAUDE_CODE_OAUTH_TOKEN" not in argv
    assert "synthetic-secret-token-value" not in result.stdout
    assert "synthetic-secret-token-value" not in result.stderr
    launch_spec.assert_no_container_credential_env(argv)


def test_detach_codex_harness_needs_no_optin_tokenless() -> None:
    # Codex detached carries no OAUTH token, so the guard does not apply.
    argv = dry_run_argv(run_wrapper("--detach", "tui"))
    assert "-d" in argv
    assert "CLAUDE_CODE_OAUTH_TOKEN" not in argv


def test_custom_container_name_propagates_to_name_flag() -> None:
    argv = dry_run_argv(
        run_wrapper("--detach", "tui", CE_VPS_CONTAINER_NAME="ce-vps-custom-seat")
    )

    assert argv[argv.index("--name") + 1] == "ce-vps-custom-seat"
    assert "--rm" not in argv


def test_detach_env_triggers_detached_argv() -> None:
    argv = dry_run_argv(run_wrapper("tui", CE_VPS_DETACH="1"))

    assert "-d" in argv
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-codex"
    assert "--rm" not in argv


def test_foreground_exec_keeps_rm_without_detach_or_name_flags() -> None:
    argv = dry_run_argv(run_wrapper("--foreground", "exec", "hello"))

    assert "--rm" in argv
    assert "-d" not in argv
    assert "--name" not in argv
    assert "-it" in argv


def test_foreground_tui_uses_canonical_container_name_without_detach() -> None:
    argv = dry_run_argv(run_wrapper("--foreground", "tui"))

    assert "--rm" in argv
    assert "-d" not in argv
    assert "--name" in argv
    assert argv[argv.index("--name") + 1] == "ce-vps-codex"
    assert "-it" in argv


def test_foreground_env_switch_keeps_legacy_rm_path() -> None:
    argv = dry_run_argv(run_wrapper("tui", CE_VPS_FOREGROUND="1"))

    assert "--rm" in argv
    assert "-d" not in argv


def test_detach_dry_run_still_generates_pretrusting_contained_config(
    tmp_path: Path,
) -> None:
    config_path = tmp_path / "contained-codex.toml"

    argv = dry_run_argv(
        run_wrapper("--detach", "tui", CE_VPS_CONTAINED_CODEX_CONFIG=str(config_path))
    )

    assert any(
        arg
        == f"type=bind,source={config_path},target=/home/seat/.codex/config.toml,readonly"
        for arg in argv
    )
    assert config_path.read_text(encoding="utf-8") == expected_contained_codex_config()


def test_no_herdr_socket_path_carrier_or_host_socket_mount_reaches_docker_argv() -> None:
    result = run_wrapper(
        "tui",
        HERDR_SOCKET_PATH="/run/user/1000/herdr.sock",
        HERDR_SOCKET="/run/user/1000/legacy-herdr.sock",
        CE_DGX_HERDR_SOCKET_PATH="/run/user/1000/ce-dgx-herdr.sock",
        CE_DGX_SOCKET_PATH="/run/user/1000/ce-dgx-generic.sock",
    )

    argv = dry_run_argv(result)
    rendered = result.stdout

    assert "HERDR_SOCKET" not in rendered
    assert "CE_DGX_HERDR_SOCKET_PATH" not in rendered
    assert not re.search(r"CE_DGX_[A-Z0-9_]*SOCKET[A-Z0-9_]*=", rendered)
    assert "/run/user/1000/herdr.sock" not in rendered
    assert "/run/user/1000/legacy-herdr.sock" not in rendered
    assert "/run/user/1000/ce-dgx-herdr.sock" not in rendered
    assert "/run/user/1000/ce-dgx-generic.sock" not in rendered
    assert not any(
        arg.startswith("type=bind,") and (".sock" in arg or "socket" in arg.lower())
        for arg in argv
    )


# ---------------------------------------------------------------------------
# Egress self-push broker socket mount (ce-ops#265)
# ---------------------------------------------------------------------------


def test_egress_broker_socket_mount_requires_explicit_seat_id() -> None:
    result = run_wrapper(
        "tui",
        CE_VPS_EGRESS_BROKER_SOCKET="/run/user/1000/creator-engine/egress-broker/dev-3.sock",
    )

    assert result.returncode == 2
    assert "CE_VPS_SEAT_ID must be set explicitly" in result.stderr


def test_egress_broker_socket_mount_rejects_non_broker_seat_id() -> None:
    result = run_wrapper(
        "tui",
        CE_VPS_SEAT_ID="ce-vps-codex",
        CE_VPS_EGRESS_BROKER_SOCKET="/run/user/1000/creator-engine/egress-broker/dev-3.sock",
    )

    assert result.returncode == 2
    assert "CE_VPS_SEAT_ID must be a broker seat id like dev-3" in result.stderr


def test_egress_broker_socket_mount_rejects_empty_explicit_seat_id() -> None:
    result = run_wrapper(
        "tui",
        CE_VPS_SEAT_ID="",
        CE_VPS_EGRESS_BROKER_SOCKET="/run/user/1000/creator-engine/egress-broker/dev-3.sock",
    )

    assert result.returncode == 2
    assert "CE_VPS_SEAT_ID must be a broker seat id like dev-3" in result.stderr


def test_egress_broker_socket_mounts_parent_directory_and_value_env() -> None:
    host_socket = "/run/user/1000/creator-engine/egress-broker/dev-3.sock"
    container_socket = "/run/ce-egress/dev-3.sock"
    argv = dry_run_argv(
        run_wrapper(
            "tui",
            CE_VPS_SEAT_ID="dev-3",
            CE_VPS_EGRESS_BROKER_SOCKET=host_socket,
            GITHUB_TOKEN="ghp_0123456789abcdef0123456789abcdef0123",
            GH_TOKEN="ghs_0123456789abcdef0123456789abcdef0123",
            OPENBAO_TOKEN="hvs.0123456789abcdef",
            CE_APP_KEY="-----BEGIN PRIVATE KEY-----",
            SSH_AUTH_SOCK="/tmp/ssh-agent.sock",
            DOCKER_HOST="unix:///var/run/docker.sock",
            CE_EGRESS_BROKER_CONFIG="/home/ce/.ce-egress/broker.json",
        )
    )

    assert f"CE_EGRESS_BROKER_SOCKET={container_socket}" in argv
    assert "CE_SEAT_ID=dev-3" in argv
    assert f"CE_VPS_EGRESS_BROKER_SOCKET={host_socket}" not in argv
    assert not any("CE_VPS_CONTAINER_EGRESS_BROKER_SOCKET=" in arg for arg in argv)
    assert any(
        arg == "type=bind,source=/run/user/1000/creator-engine/egress-broker,target=/run/ce-egress,readonly"
        for arg in argv
    )
    rendered = "\n".join(argv)
    assert "ghp_0123456789abcdef0123456789abcdef0123" not in rendered
    assert "ghs_0123456789abcdef0123456789abcdef0123" not in rendered
    assert "hvs.0123456789abcdef" not in rendered
    assert "-----BEGIN PRIVATE KEY-----" not in rendered
    assert "/tmp/ssh-agent.sock" not in rendered
    assert "/var/run/docker.sock" not in rendered
    assert "/home/ce/.ce-egress/broker.json" not in rendered
    assert not any("GITHUB_TOKEN" in arg or "GH_TOKEN" in arg for arg in argv)
    assert not any(
        "OPENBAO" in arg
        or "APP_KEY" in arg
        or "SSH_AUTH_SOCK" in arg
        or "DOCKER_HOST" in arg
        or "CE_EGRESS_BROKER_CONFIG" in arg
        for arg in argv
    )


def test_egress_broker_socket_mount_accepts_explicit_matching_container_basename() -> None:
    host_socket = "/run/user/1000/creator-engine/egress-broker/dev-3.sock"
    container_socket = "/broker/dev-3.sock"
    argv = dry_run_argv(
        run_wrapper(
            "tui",
            CE_VPS_SEAT_ID="dev-3",
            CE_VPS_EGRESS_BROKER_SOCKET=host_socket,
            CE_VPS_CONTAINER_EGRESS_BROKER_SOCKET=container_socket,
        )
    )

    assert f"CE_EGRESS_BROKER_SOCKET={container_socket}" in argv
    assert any(
        arg == "type=bind,source=/run/user/1000/creator-engine/egress-broker,target=/broker,readonly"
        for arg in argv
    )


def test_egress_broker_socket_mount_rejects_mismatched_container_basename() -> None:
    result = run_wrapper(
        "tui",
        CE_VPS_SEAT_ID="dev-3",
        CE_VPS_EGRESS_BROKER_SOCKET="/run/user/1000/creator-engine/egress-broker/dev-3.sock",
        CE_VPS_CONTAINER_EGRESS_BROKER_SOCKET="/broker/not-dev-3.sock",
    )

    assert result.returncode == 2
    assert "CE_VPS_CONTAINER_EGRESS_BROKER_SOCKET basename must match" in result.stderr


def test_no_egress_broker_mount_when_socket_unset() -> None:
    argv = dry_run_argv(run_wrapper("tui"))

    assert not any("CE_EGRESS_BROKER_SOCKET=" in arg for arg in argv)
    assert not any("CE_SEAT_ID=" in arg for arg in argv)
    assert not any(
        arg.startswith("type=bind,") and "egress" in arg.lower() for arg in argv
    )


def test_egress_broker_socket_absent_fails_closed_before_docker_run_under_nondry_run(
    tmp_path: Path,
) -> None:
    missing_socket = "/run/user/1000/creator-engine/egress-broker/missing.sock"
    result = run_live_wrapper_with_fake_docker(
        tmp_path,
        "tui",
        CE_VPS_SEAT_ID="dev-3",
        CE_VPS_EGRESS_BROKER_SOCKET=missing_socket,
    )

    assert result.returncode == 66
    assert f"egress broker socket not found: {missing_socket}" in result.stderr
    assert "unexpected docker invocation" not in result.stderr


# ---------------------------------------------------------------------------
# Egress self-review broker socket mount
# ---------------------------------------------------------------------------


def test_egress_self_review_socket_mounts_parent_directory_and_value_env() -> None:
    host_socket = "/run/user/1000/creator-engine/egress-broker/dev-3-review.sock"
    container_socket = "/run/ce-egress/dev-3-review.sock"
    argv = dry_run_argv(
        run_wrapper(
            "tui",
            CE_VPS_SEAT_ID="dev-3",
            CE_VPS_EGRESS_SELF_REVIEW_SOCKET=host_socket,
        )
    )

    assert f"CE_EGRESS_SELF_REVIEW_SOCKET={container_socket}" in argv
    assert "CE_SEAT_ID=dev-3" in argv
    assert any(
        arg == "type=bind,source=/run/user/1000/creator-engine/egress-broker,target=/run/ce-egress,readonly"
        for arg in argv
    )


def test_egress_self_review_socket_mount_rejects_mismatched_container_basename() -> None:
    result = run_wrapper(
        "tui",
        CE_VPS_SEAT_ID="dev-3",
        CE_VPS_EGRESS_SELF_REVIEW_SOCKET="/run/user/1000/creator-engine/egress-broker/dev-3-review.sock",
        CE_VPS_CONTAINER_EGRESS_SELF_REVIEW_SOCKET="/broker/review.sock",
    )

    assert result.returncode == 2
    assert "CE_VPS_CONTAINER_EGRESS_SELF_REVIEW_SOCKET basename must match" in result.stderr


def test_egress_broker_and_self_review_sockets_sharing_a_directory_dedupe_mount(
) -> None:
    # Real dev-3 layout (deploy/systemd/ce-egress-broker.socket and
    # ce-egress-self-review.socket ListenStream): both sockets live side by
    # side in /run/ce-egress, so the parent-directory mounts computed for
    # each socket are identical. `docker run` rejects two `--mount` flags
    # with the same destination ("Duplicate mount point"); the launcher must
    # emit that mount exactly once while both sockets stay reachable inside
    # the container via the single shared directory mount.
    broker_host_socket = "/run/ce-egress/dev-3.sock"
    review_host_socket = "/run/ce-egress/dev-3-review.sock"
    argv = dry_run_argv(
        run_wrapper(
            "tui",
            CE_VPS_SEAT_ID="dev-3",
            CE_VPS_EGRESS_BROKER_SOCKET=broker_host_socket,
            CE_VPS_EGRESS_SELF_REVIEW_SOCKET=review_host_socket,
        )
    )

    mount_flags = [
        argv[index + 1] for index, arg in enumerate(argv) if arg == "--mount"
    ]
    egress_dir_mounts = [
        spec
        for spec in mount_flags
        if spec == "type=bind,source=/run/ce-egress,target=/run/ce-egress,readonly"
    ]

    # Exactly one mount for the shared directory (no duplicate destination).
    assert egress_dir_mounts == [
        "type=bind,source=/run/ce-egress,target=/run/ce-egress,readonly"
    ]
    # Docker would reject a duplicate destination outright; assert the full
    # set of mount destinations has no repeats.
    destinations = [spec.split("target=", 1)[1].split(",", 1)[0] for spec in mount_flags]
    assert len(destinations) == len(set(destinations)), (
        f"duplicate --mount destination(s) in argv, docker would reject: {mount_flags}"
    )

    # Both sockets remain reachable: their env vars still point at distinct
    # container paths inside the single shared mounted directory.
    assert "CE_EGRESS_BROKER_SOCKET=/run/ce-egress/dev-3.sock" in argv
    assert "CE_EGRESS_SELF_REVIEW_SOCKET=/run/ce-egress/dev-3-review.sock" in argv


def test_egress_broker_and_self_review_sockets_in_different_directories_both_mount() -> None:
    # Both sockets default their container path to /run/ce-egress/<basename>,
    # which would collide on the *destination* even when the host sources
    # differ. Exercise the genuinely-distinct-directories case by giving each
    # socket its own explicit (basename-matching) container path, and confirm
    # both parent-directory mounts are still emitted with no duplicate
    # destination.
    broker_host_socket = "/run/user/1000/creator-engine/egress-broker/dev-3.sock"
    review_host_socket = "/run/user/1000/creator-engine/egress-review/dev-3-review.sock"
    argv = dry_run_argv(
        run_wrapper(
            "tui",
            CE_VPS_SEAT_ID="dev-3",
            CE_VPS_EGRESS_BROKER_SOCKET=broker_host_socket,
            CE_VPS_CONTAINER_EGRESS_BROKER_SOCKET="/run/ce-egress-broker/dev-3.sock",
            CE_VPS_EGRESS_SELF_REVIEW_SOCKET=review_host_socket,
            CE_VPS_CONTAINER_EGRESS_SELF_REVIEW_SOCKET="/run/ce-egress-review/dev-3-review.sock",
        )
    )

    mount_flags = [
        argv[index + 1] for index, arg in enumerate(argv) if arg == "--mount"
    ]

    assert (
        "type=bind,source=/run/user/1000/creator-engine/egress-broker,target=/run/ce-egress-broker,readonly"
        in mount_flags
    )
    assert (
        "type=bind,source=/run/user/1000/creator-engine/egress-review,target=/run/ce-egress-review,readonly"
        in mount_flags
    )
    destinations = [spec.split("target=", 1)[1].split(",", 1)[0] for spec in mount_flags]
    assert len(destinations) == len(set(destinations)), (
        f"duplicate --mount destination(s) in argv, docker would reject: {mount_flags}"
    )
